.TH XDPR 1 "1 March 1988" "X Version 11"
.SH NAME
xdpr \- dump an X window directly to the printer
.SH SYNOPSIS
.B xdpr
[-option ...]
.SH DESCRIPTION
\fIXdpr\fP runs the commands 
.IR xwd (1),
.IR xpr (1), and
.IR lpr (1)
to dump an X window, process it for the LN03 laser printer, and print
it out.  This is the easiest way to get a printout of a window.
\fIXdpr\fP by default will print the largest possible representation 
of the window on the output page.
.PP
.TP
.B -P\fIprinter\fP
This option specifies the name of the printer to be used.
.TP
.B \-display \fIhost\fP:\fIdisplay\fP
This option specifies the X server to contact.
.PP
Any other arguments 
will be passed as arguments to the 
.IR xpr(1)
command.
.SH SEE ALSO
xwd(1), xpr(1), xwud(1), X(1)
.SH ENVIRONMENT
DISPLAY - for which display to use be default.
.SH AUTHOR
.PP
Copyright 1985, Massachusetts Institute of Technology
.PP
Michael R. Gretzinger, MIT Project Athena
.PP
Jim Gettys, MIT Project Athena
