LIBRARY XTST
VERSION LIBRARY_VERSION
EXPORTS
 XRecordChangeCG
 XRecordCreateCG
 XRecordDisableCG
 XRecordEnableCG
 XRecordEnableCGAsync
 XRecordFreeCG
 XRecordGetCG
 XRecordQueryVersion
 XTestCompareCurrentCursorWithWindow
 XTestCompareCursorWithWindow
 XTestDiscard
 XTestFakeButtonEvent
 XTestFakeDeviceButtonEvent
 XTestFakeDeviceKeyEvent
 XTestFakeDeviceMotionEvent
 XTestFakeKeyEvent
 XTestFakeMotionEvent
 XTestFakeProximityEvent
 XTestFakeRelativeMotionEvent
 XTestGrabControl
 XTestQueryExtension
 XTestSetGContextOfGC
 XTestSetVisualIDOfVisual
