# $XConsortium: Makefile.ini,v 1.16 93/09/04 15:54:19 rws Exp $

SHELL = /bin/sh
RM = rm -f
MV = mv
MAKE = make
NMAKE = nmake
WORLDOPTS = -k
WIN32WORLDOPTS = -i
TOP = .
CURRENT_DIR = .
CONFIGSRC = $(TOP)/config
IMAKESRC = $(CONFIGSRC)/imake
IRULESRC = $(CONFIGSRC)/cf
IMAKE = $(IMAKESRC)/imake
IMAKE_CMD = $(IMAKE) -I$(IRULESRC) $(IMAKE_DEFINES)
FLAGS = $(MFLAGS) -f Makefile.ini BOOTSTRAPCFLAGS="$(BOOTSTRAPCFLAGS)"

all:
	@echo "Please use make World, and set BOOTSTRAPCFLAGS if necessary."
	@echo "Do not name your log file make.log or it will be deleted."
	@echo "Check the configuration parameters in the config directory,
	@echo "and read the release notes carefully before proceeding."
	@echo "If the top-level Makefile gets corrupted, copy Makefile.ini
	@echo "to Makefile and try again."

World:
	@echo ""
	@echo "Building Release 6alpha of the X Window System"
	@echo ""
	@echo "##############################################################"
	@echo "# Did you remember to check the configuration parameters in  #"
	@echo "# the directory ./config and set BOOTSTRAPCFLAGS if needed?  #"
	@echo "##############################################################"
	@echo ""
	@date
	@echo ""
	cd $(IMAKESRC); $(MAKE) $(FLAGS) clean; $(MAKE) $(FLAGS)
	-$(RM) Makefile.bak; $(MV) Makefile Makefile.bak
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)
	$(MAKE) $(MFLAGS) Makefiles
	$(MAKE) $(MFLAGS) clean
	$(MAKE) $(MFLAGS) includes
	$(MAKE) $(MFLAGS) depend
	$(MAKE) $(MFLAGS) $(WORLDOPTS)
	@echo ""
	@date
	@echo ""
	@echo "Full build of Release 6alpha of the X Window System complete."
	@echo ""

Makefile:
	cd $(IMAKESRC); $(MAKE) $(FLAGS)
	-$(RM) Makefile.bak; $(MV) Makefile Makefile.bak
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

all.Win32:
	@echo Please use make World.Win32
	@echo Do not name your log file make.log or it will be deleted.
	@echo Check the configuration parameters in the config directory.
	@echo and read the release notes carefully before proceeding.
	@echo If the top-level Makefile gets corrupted, copy Makefile.ini
	@echo to Makefile and try again.

World.Win32:
	@echo :
	@echo Building Release 6alpha of the X Window System
	@echo :
	@echo :
	cd $(IMAKESRC)
	$(NMAKE) -f Makefile.ini clean.Win32
	$(NMAKE) -f Makefile.ini imake.exe
	cd ..\..
	-if exist Makefile.bak del Makefile.bak
	-if exist Makefile ren Makefile Makefile.bak
	$(IMAKE:/=\) -I$(IRULESRC) $(IMAKE_DEFINES) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)
	$(NMAKE) $(MFLAGS) Makefiles
	$(NMAKE) $(MFLAGS) clean
	$(NMAKE) $(MFLAGS) includes
	$(NMAKE) $(MFLAGS) depend
	$(NMAKE) $(MFLAGS) $(WIN32WORLDOPTS)
	@echo :
	@echo :
	@echo Full build of Release 6alpha of the X Window System complete.
	@echo :
