.\" $XConsortium: fstobdf.man,v 1.4 94/04/11 21:46:02 gildea Exp $
.\" Copyright 1990, Network Computing Devices
.\" Copyright 1990 Massachusetts Institute of Technology
.\"
.\" Permission to use, copy, modify, distribute, and sell this software and
.\" its documentation for any purpose is hereby granted without fee, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in advertising or
.\" publicity pertaining to distribution of the software without specific,
.\" written prior permission.  M.I.T. makes no representations about the
.\" suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH FSTOBDF 1 "Release 6" "X Version 11"
.SH NAME
fstobdf \- generate BDF font from X font server
.SH SYNOPSIS
.B "fstobdf"
[
.B \-server
.I server
]
.B \-fn
.I fontname
.SH DESCRIPTION
The \fIfstobdf\fP program reads a font from a font server and prints a BDF
file on the standard output that may be used to recreate the font.
This is useful in testing servers, debugging font metrics, and reproducing 
lost BDF files.
.SH OPTIONS
.TP 8
.B \-server \fIservername\fP
This option specifies the server from which the font should be read.
.TP 8
.B \-fn \fIfontname\fP
This option specifies the font for which a BDF file should be generated.
.SH ENVIRONMENT
.TP 8
.B FONTSERVER
default server to use
.SH "SEE ALSO"
xfs(1), bdftopcf(1), fslsfonts(1)
.SH AUTHOR
Olaf Brandt, Network Computing Devices
.br
Dave Lemke, Network Computing Devices
.br
.sp
Jim Fulton, MIT X Consortium
