.\" $XConsortium: mkdirhier.man,v 1.4 93/08/02 11:14:12 gildea Exp $
.TH MKDIRHIER 1 "Release 6" "X Version 11"
.SH NAME
mkdirhier \- makes a directory hierarchy
.SH SYNOPSIS
.B mkdirhier
directory ...
.SH DESCRIPTION
The
.I mkdirhier
command creates the specified directories. Unlike
.I mkdir
if any of the parent directories of the specified directory
do not exist, it creates them as well.
.SH "SEE ALSO"
mkdir(1)
