.TH XEDIT 1 "1 March 1988" "X Version 11"
.UC 4
.SH NAME
xedit \- animate text
.SH SYNOPSIS
.B Xedit
[-r] [-display \fIhost\fP:\fIdpy\fP]
.SH DESCRIPTION
.I Xedit
displays text.  It accepts the standard X toolkit command line options.
.SH BUGS
There are lots of bugs.  There are lots of lacking features.
Does not yet implement 3d extensions.
