.TH XLOAD 1 "1 March 1988" "X Version 11"
.SH NAME
xload - X window system load average display
.SH SYNOPSIS
.B xload
[ option ] ...
.SH DESCRIPTION
The 
.I xload 
program continuously displays the system load average under the
.I X
window system.  It
creates a window in which the load average is represented as a bar graph
with n divisions. Each division represents one unit of load average.
The name of the host is displayed in the upper left corner.  This program
is nothing more than a wrapper around the Athena Load widget.
.SH OPTIONS
.PP
This program accepts all of the standard X toolkit options along with its
own specific options shown below:
.PP
.TP 8
.B \-scale \fIinteger\fP
This option specifies the minimum number of divisions on the graph (default 1).
.I Xload
is free to use more divisions if the load gets too high to display,
but it will never use fewer divisions than this.
.PP
.TP 8
.B \-update \fIseconds\fP
This option specifies the frequency in seconds with which
.I xload
updates its display (except if the
.I xload
window is obscured and then exposed, immediate redisplay occurs).  The default
update frequency is 5 seconds.  Specification of a frequency
less than 5 seconds is ignored and the default frequency is used instead.
.PP
The following standard X toolkit arguments are commonly used
with \fIxload\fP.
.PP
.TP 8
.B \-bd \fIcolor\fP
This option specifies the border color.
The default color is ``black''.
.PP
.TP 8
.B \-bg \fIcolor\fP
This option specifies the background color.
The default color is ``white''.
.PP
.TP 8
.B \-bw \fIpixels\fP
This option specifies the width in pixels of the border around the
.I xload
window. The default value is 3 pixels.
.PP
.TP 8
.B \-fg \fIcolor\fP
This option specifies the graph color.
The default color is ``black''.
.PP
.TP 8
.B \-fn \fIfontname\fP
The hostname will be displayed in the specified font (if none
is specified, this defaults to 6x10).
.PP
.TP 8
.B \-rv
The foreground and background colors
are reversed.
.PP
.TP 8
.B \-geometry \fIgeometry\fP
The load graph window is created with the specified
size and location
determined
by the supplied geometry specification.
See \fIX(1)\fP for a full explanation.
.PP
.TP 8
.B \-display \fIhost\fP:\fIdisplay\fP
Normally,
.I xload
gets the host and display number to use from the environment
variable ``DISPLAY''.  Either or both can be specified with this option.
.I host
specifies which machine to create the
.I xload
window on, and
.I display
specifies the display number.
For example,
``xload -display nehi:0'' creates an
.I xload
on display 0 on machine nehi. Either value can be defaulted
by omission but ``:'' is necessary to specify one or both.
.PP
.TP 8
.B \-xrm \fIresourcestring\fP
This option can be used to set resources that do not have command line
arguments.
.SH X DEFAULTS
.PP
This program uses the 
.I Load
widget in the X Toolkit.  It understands all of the core resource names and
classes as well as:
.TP 8
.B width (class Width)
Specifies the width of the load average graph.
.TP 8
.B height (class Height)
Specifies the height of the load average graph.
.TP 8
.B update (class Interval)
Specifies the frequency in seconds at which the load should be redisplayed.
.TP 8
.B scale (class Scale)
Specifies the initial number of ticks on the graph.  The default is 1.
.TP 8
.B minScale (class Scale)
Specifies the minimum number of ticks that will be displayed.  The default
is 1.
.TP 8
.B foreground (class Foreground)
Specifies the color for the graph.  Using the class specifies the
color for all things that normally would appear in the foreground color.
The default is ``black'' since the core default for background is ``white.''
.TP 8
.B label (class Label)
Specifies the label to use on the graph.  The default is the hostname.
.TP 8
.B font (class Font)
Specifies the font to be used for the label.  The default is ``fixed.''
.TP 8
.B reverseVideo (class ReverseVideo)
Specifies that the foreground and background should be reversed.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY 
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources 
stored in the RESOURCE_MANAGER property.
.SH SEE ALSO
X(1), xrdb(1), X(8C), mem(4), select(2)
.SH DIAGNOSTICS
Unable to open display or create window. Unable to open /dev/kmem.
Unable to query window for dimensions. Various X errors.
.SH BUGS
.I xload
requires the ability to open and read /dev/kmem. On most systems, this requires
the suid bit set with root ownership or the sgid bit set and membership in 
the same group as /dev/kmem. 
.PP
Border color has to be explicitly specified when reverse video is used.
.SH AUTHORS
Copyright (c) 1985, Massachusetts Institute of Technology.
.br
K. Shane Hartman (MIT-LCS) and Stuart A. Malone (MIT-LCS);
.br
features added by Jim Gettys (MIT-Athena), Bob Scheifler (MIT-LCS),
and Tony Della Fera (MIT-Athena)
