.TH XMAG 1 "28 January 1991" "X Version 11"
.SH NAME
xmag \- magnify parts of the screen.

.SH SYNOPSIS
xmag [-freq dynamicfreq] [-mag magfactor] [-source geom] [-z] [-toolkitoption ...]
.SH DESCRIPTION
The xmag program allows you to magnify portions of the screen.  If no 
explicit region is specified, a square with the pointer in the upper left 
corner is displayed indicating the area to be enlarged.  The area can be 
draged out to the desired size by pressing Button 2.  Once a region has 
been selected, a window is popped up showing a blown up version of the region 
in which each pixel in the source image is represented by a small square of 
the same color.  Pressing Button1 on the pointer in the enlargement window 
shows a small pixel information window displaying the position and RGB value
of the pixel under the pointer until the button is released.  Pressing ``Q'' 
or ``^C'' in the enlargement window exits the program.  The application has
3 buttons across its top.  Close deletes this particular magnification 
instance.  Replace brings up the rubber band selector again to select another
region for this magnification instance.  New brings up the rubber band
selector to create a new magnification instance.  Note that resizeing xmag
resizes the magnification area.  Xmag also preserves colormaps, visuals, and
window depth from the target magnification area.
.SH WIDGETS
Xmag uses the X Toolkit Intrinsics and the Athena Widget Set.
The main part of the toplevel is Scale widget described below.  
For more information, see the Athena Widget Set documentation.
Below is the widget structure of the xmag application.
Indentation indicates hierarchical  structure.  The widget class
name is given first, followed by the widget instance name.
.sp
.nf
	Xmag xmag
		RootWindow root
		TopLevelShell xmag
			Paned pane1
				Panned pane2
					Command close
					Command replace
					Command new
					Label helpLabel
				Panned pane2
					Scale scale
		OverrideShell pixShell 
			Label pixLabel
		
.fi
.SH OPTIONS
.TP 4
.B\-source\fI geom\fP
This option specifies the size and/or location of the source region 
on the screen.  By default, a 64x64 square is provided for the user to select 
an area of the screen.
.TP 4
.B\-mag\fI integer\fP
This option indicates the magnification to be used. 5x is the default.
.SH COPYRIGHT
Copyright 1991, Massachusetts Institute of Technology.
.br
See \fIX(1)\fP for a full statement of rights and permissions.
.SH SEE ALSO
X(1), xwd(1)
.SH AUTHOR
Dave Sternlicht and Davor Matic, MIT X Consortium.

