.\" $XConsortium: fsinfo.man,v 1.4 94/04/11 21:37:47 gildea Exp $
.\" Copyright 1991, Network Computing Devices, Inc
.\" Copyright 1993 Massachusetts Institute of Technology
.\"
.\" Permission to use, copy, modify, distribute, and sell this software and
.\" its documentation for any purpose is hereby granted without fee, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in advertising or
.\" publicity pertaining to distribution of the software without specific,
.\" written prior permission.  M.I.T. makes no representations about the
.\" suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH FSINFO 1 "Release 6" "X Version 11"
.SH NAME
fsinfo \- X font server information utility
.SH SYNOPSIS
.B "fsinfo"
[\-server \fIservername\fP]
.SH DESCRIPTION
.PP
.I Fsinfo
is a utility for displaying information about an X font server.  It is used to 
examine the
capabilities of a server, the predefined values for various parameters used
in communicating between clients and the server, and the font catalogues
and alternate servers that are available.
.SH EXAMPLE
.PP
The following shows a sample produced by
.I fsinfo.
.PP
.nf
name of server:	hansen:7100
version number:	1
vendor string:	Font Server Prototype
vendor release number:	17
maximum request size:	16384 longwords (65536 bytes)
number of catalogues:	1
	all
Number of alternate servers: 2
    #0	hansen:7101
    #1	hansen:7102
number of extensions:	0
.fi

.SH ENVIRONMENT
.PP
.TP 8
.B FONTSERVER
To get the default fontserver.
.SH "SEE ALSO"
xfs(1), fslsfonts(1)
.SH AUTHOR
Dave Lemke, Network Computing Devices, Inc
