#!/bin/csh -f

cd /
if ( ! $?TERM ) then
  setenv TERM vt100
  unsetenv TERMCAP
endif
if ( "$TERM" == "dialup" || "$TERM" == "network" ) then
  setenv TERM vt100
  unsetenv TERMCAP
endif
clear
if ( $?A2XOPTS ) then
  echo exec a2x $* $A2XOPTS
else
  echo exec a2x $*
endif
