/* $XConsortium: tests.c,v 1.5 93/08/19 09:41:50 rws Exp $ */

/**** module do_tests.c ****/
/******************************************************************************
				NOTICE
                              
This software is being provided by AGE Logic, Inc. and MIT under the
following license.  By obtaining, using and/or copying this software,
you agree that you have read, understood, and will comply with these
terms and conditions:

     Permission to use, copy, modify, distribute and sell this
     software and its documentation for any purpose and without
     fee or royalty and to grant others any or all rights granted
     herein is hereby granted, provided that you agree to comply
     with the following copyright notice and statements, including
     the disclaimer, and that the same appears on all copies and
     derivative works of the software and documentation you make.
     
     "Copyright 1993 by AGE Logic, Inc. and the Massachusetts
     Institute of Technology"
     
     THIS SOFTWARE IS PROVIDED "AS IS".  AGE LOGIC AND MIT MAKE NO
     REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED.  By way of
     example, but not limitation, AGE LOGIC AND MIT MAKE NO
     REPRESENTATIONS OR WARRANTIES OF MERCHANTABILITY OR FITNESS
     FOR ANY PARTICULAR PURPOSE OR THAT THE SOFTWARE DOES NOT
     INFRINGE THIRD-PARTY PROPRIETARY RIGHTS.  AGE LOGIC AND MIT
     SHALL BEAR NO LIABILITY FOR ANY USE OF THIS SOFTWARE.  IN NO
     EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT,
     INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS
     OF PROFITS, REVENUE, DATA OR USE, INCURRED BY EITHER PARTY OR
     ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT OR
     BASED ON A WARRANTY, EVEN IF AGE LOGIC OR MIT OR LICENSEES
     HEREUNDER HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
     DAMAGES.
    
     The names of AGE Logic, Inc. and MIT may not be used in
     advertising or publicity pertaining to this software without
     specific, written prior permission from AGE Logic and MIT.

     Title to this software shall at all times remain with AGE
     Logic, Inc.
*****************************************************************************
  
	do_tests.c -- test configuration

	Syd Logan -- AGE Logic, Inc. July, 1993 - MIT Alpha release 
  
*****************************************************************************/
#include "xieperf.h"

extern Bool InitImportPhoto();
extern Bool InitConvertToIndex();
extern Bool InitImportLUT();
extern Bool InitImportROI();
extern Bool InitPurgeColorList();
extern Bool InitDitherFloMap();
extern Bool InitImportDrawablePixmap();
extern Bool InitImportDrawableWindow();
extern Bool InitQueryTechniques();
extern Bool InitQueryColorList();
extern Bool InitQueryPhotomap();
extern Bool InitQueryPhotoflo();
extern Bool InitPasteUp();
extern Bool InitGeometry();
extern Bool InitGeometryFAX();
extern Bool InitSimpleFlo();
extern Bool InitAbort();
extern Bool InitAwait();
extern Bool InitCreateDestroyPhotoflo();
extern Bool InitCreateDestroy();
extern Bool InitSimpleFloMap();
extern Bool InitConstrainFlo();
extern Bool InitUnconstrainFlo();
extern Bool InitPoint();
extern Bool InitModifyROI();
extern Bool InitModifyPoint();
extern Bool InitModifySimple();
extern Bool InitRedefine();
extern Bool InitBlendMonadic();
extern Bool InitBlendDyadic();
extern Bool InitROIBlendMonadic();
extern Bool InitROIBlendDyadic();
extern Bool InitLogicalMonadic();
extern Bool InitLogicalDyadic();
extern Bool InitROILogicalMonadic();
extern Bool InitROILogicalDyadic();
extern Bool InitImportClientPhoto();
extern Bool InitImportClientLUT();
extern Bool InitImportClientROI();
extern Bool InitExportClientPhoto();
extern Bool InitExportClientLUT();
extern Bool InitExportClientROI();
extern void DoConvertToIndex();
extern void DoCreateDestroyColorList();
extern void DoCreateDestroyLUT();
extern void DoCreateDestroyPhotomap();
extern void DoCreateDestroyROI();
extern void DoCreateDestroyPhotospace();
extern void DoCreateDestroyPhotoflo();
extern void DoAbort();
extern void DoAwait();
extern void DoGeometry();
extern void DoGeometryFAX();
extern void DoPasteUp();
extern void DoSimpleFloImmediateData();
extern void DoSimpleFloStoredData();
extern void DoSimpleFloImmediatePhotomap();
extern void DoSimpleFloStoredPhotomap();
extern void DoSimpleFloImmediatePhotomapToDrawable();
extern void DoSimpleFloStoredPhotomapToDrawable();
extern void DoSimpleFloMapImmediateData();
extern void DoSimpleFloMapStoredData();
extern void DoUnconstrainFloMapImmediate();
extern void DoUnconstrainFloMapStored();
extern void DoConstrainFloMapImmediate();
extern void DoConstrainFloMapStored();
extern void DoDitherFloMapImmediate();
extern void DoDitherFloMapStored();
extern void DoPointImmediate();
extern void DoPointStored();
extern void DoROIBlendDyadicImmediate();
extern void DoROIBlendMonadicImmediate();
extern void DoBlendDyadicImmediate();
extern void DoBlendMonadicImmediate();
extern void DoLogicalDyadicImmediate();
extern void DoLogicalMonadicImmediate();
extern void DoROILogicalDyadicImmediate();
extern void DoROILogicalMonadicImmediate();
extern void DoImportPhotoImmediate();
extern void DoImportPhotoStored();
extern void DoImportLUTImmediate();
extern void DoImportLUTStored();
extern void DoImportROIImmediate();
extern void DoImportROIStored();
extern void DoExportClientPhotoImmediate();
extern void DoExportClientPhotoStored();
extern void DoExportClientLUTImmediate();
extern void DoExportClientLUTStored();
extern void DoExportClientROIImmediate();
extern void DoExportClientROIStored();
extern void DoImportDrawablePixmapImmediate();
extern void DoImportDrawableWindowImmediate();
extern void DoImportDrawablePlanePixmapImmediate();
extern void DoImportDrawablePlaneWindowImmediate();
extern void DoImportClientPhotoImmediate();
extern void DoImportClientPhotoStored();
extern void DoImportClientLUTImmediate();
extern void DoImportClientLUTStored();
extern void DoImportClientROIImmediate();
extern void DoImportClientROIStored();
extern void DoSimpleFloMapClientPhotoImmediateData();
extern void DoSimpleFloMapClientPhotoStoredData();
extern void DoSimpleFloMapDrawPlanesImmediateData();
extern void DoSimpleFloMapDrawPlanesStoredData();
extern void DoQueryTechniques();
extern void DoQueryColorList();
extern void DoQueryPhotomap();
extern void DoQueryPhotoflo();
extern void DoPurgeColorList();
extern void DoModifyROI();
extern void DoModifyPoint();
extern void DoModifySimple();
extern void DoRedefine();
extern void EndConvertToIndex();
extern void EndPasteUp();
extern void EndGeometry();
extern void EndGeometryFAX();
extern void EndSimpleFlo();
extern void EndConstrainFlo();
extern void EndUnconstrainFlo();
extern void EndSimpleFloMap();
extern void EndPoint();
extern void EndROIBlendMonadic();
extern void EndROIBlendDyadic();
extern void EndBlendMonadic();
extern void EndBlendDyadic();
extern void EndLogicalMonadic();
extern void EndLogicalDyadic();
extern void EndROILogicalMonadic();
extern void EndROILogicalDyadic();
extern void EndImportClientPhoto();
extern void EndImportClientLUT();
extern void EndImportClientROI();
extern void EndExportClientPhoto();
extern void EndExportClientLUT();
extern void EndExportClientROI();
extern void EndImportPhoto();
extern void EndImportLUT();
extern void EndImportROI();
extern void EndDitherFloMap();
extern void EndCreateDestroy();
extern void EndCreateDestroyPhotoflo();
extern void EndImportDrawablePixmap();
extern void EndImportDrawableWindow();
extern void EndQueryTechniques();
extern void EndQueryColorList();
extern void EndQueryPhotomap();
extern void EndQueryPhotoflo();
extern void EndPurgeColorList();
extern void EndAbort();
extern void EndAwait();
extern void EndModifyROI();
extern void EndModifyPoint();
extern void EndModifySimple();
extern void EndRedefine();

static XIEimage ImageInfo[] = { 
	{ "image.001", 0, xieValSingleBand, 512, 512, 
	  8, 256, xieValDecodeUncompressedSingle, 
          xieValLSFirst, xieValLSFirst, 8, 4, 0, 0 },
	{ "image.002", 0, xieValSingleBand, 512, 512, 
	  8, 256, xieValDecodeUncompressedSingle, 
	  xieValLSFirst, xieValLSFirst, 8, 4, 0, 0 }, 
	{ "image.003", 0, xieValSingleBand, 512, 512, 
	  8, 256, xieValDecodeUncompressedSingle, 
	  xieValLSFirst, xieValLSFirst, 8, 4, 0, 0 }, 
	{ "image.004", 0, xieValTripleBand, 336, 270, 
	  8, 256, xieValDecodeUncompressedTriple, 
	  xieValLSFirst, xieValLSFirst, 24, 0, 0, 0 }, 
	{ "image.005", 0, xieValSingleBand, 2560, 3300, 
	  8, 2, xieValDecodeG42D, 
	  xieValLSFirst, xieValLSFirst, 8, 4, 0, 0 },
	{ "image.006", 0, xieValSingleBand, 512, 512, 
	  8, 256, xieValDecodeUncompressedSingle, 
	  xieValLSFirst, xieValLSFirst, 8, 4, 0, 0 }, 
	{ "image.007", 0, xieValSingleBand, 1728, 2100, 
	  8, 2, xieValDecodeG32D, 
	  xieValMSFirst, xieValLSFirst, 8, 4, 0, 0 }, 
	{ "image.008", 0, xieValSingleBand, 1728, 1102, 
	  8, 2, xieValDecodeG31D, 
	  xieValMSFirst, xieValLSFirst, 8, 4, 0, 0 }, 
};

static RedefineParms RedefineParmVec[] = { 
				     { { 0.0, 0.0, 0.0 }, 7, GXor, GXnor } 
				         };
static ModifyParms ModifyParmVec[] = { 
				     { { 0.0, 0.0, 0.0 }, 7, GXinvert } 
				     };
static CvtToIndexParms CvtToIndexParmVec[] = { 
				     { xieValDitherDefault } 
				             };
static UnconstrainParms UnconstrainParmVec[] = { 
				     { xieValConstrainClipScale, ClampInputs } 
				               };
static BlendParms BlendParmVec[] = { 
		{ { 0.1, 0.0, 0.0 }, 0.5, 7 },
		{ { 220.0, 0.0, 0.0 }, 255.0, 7 },
		{ { 0.0, 0.0, 0.0 }, 250.0, 7 }
				   };
static ConstrainParms ConstrainParmVec[] = { 
				     { xieValConstrainHardClip, 0 }, 
				     { xieValConstrainClipScale, ClampInputs }, 
				     { xieValConstrainClipScale, 0 } 
				           };
static DitherParms DitherParmVec[] = { 
				     { xieValDitherErrorDiffusion, Drawable }, 
				     { xieValDitherDefault, Drawable },
				     { xieValDitherDefault, DrawablePlane }
				     };
static GeometryParms GeometryParmVec[] = {
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomNearestNeighbor, 12 },
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomNearestNeighbor, 147 },
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomNearestNeighbor, 193 },
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomNearestNeighbor, 311 },
	{ GEO_TYPE_MIRRORX, 512, 512, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_MIRRORY, 512, 512, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_MIRRORXY, 512, 512, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_CROP, 256, 256, 256, 256, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 128, 128, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 256, 256, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 256, 512, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 512, 128, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 256, 768, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 128, 768, 0, 0, xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomAntialias, 12 },
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomAntialias, 147 },
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomAntialias, 193 },
	{ GEO_TYPE_ROTATE, 512, 512, 0, 0, xieValGeomAntialias, 311 },
	{ GEO_TYPE_MIRRORX, 512, 512, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_MIRRORY, 512, 512, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_MIRRORXY, 512, 512, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_CROP, 256, 256, 256, 256, xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 128, 128, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 256, 256, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 256, 512, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 512, 128, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 256, 768, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 128, 768, 0, 0, xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 512, 512, 0,0,  xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 512, 512, 0,0,  xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALE, 512, 512, 0,0,  xieValGeomNearestNeighbor, 0 },
	{ GEO_TYPE_SCALE, 512, 512, 0,0,  xieValGeomAntialias, 0 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomNearestNeighbor, 90 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomNearestNeighbor, 147 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomNearestNeighbor, 193 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomNearestNeighbor, 311 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomAntialias, 90 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomAntialias, 147 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomAntialias, 193 },
	{ GEO_TYPE_SCALEDROTATE, 512, 512, 0,0,xieValGeomAntialias, 311 }
};

static AbortParms AbortParmVec[] = { 
				     { 256, 256 } 
				   };
static AwaitParms AwaitParmVec[] = { 
				     { 256, 256 } 
			           };
static PasteUpParms PasteUpParmVec[] = { 
				     { NoOverlap },
				     { Overlap } 
			               };
static PointParms PointParmVec[] = { 
				     { 8, 8 },
				     { 1, 8 },
				     { 8, 1 },
			           };
static ImportParms ImportParmVec[] = { 
				     { NoObscure },
				     { Obscuring },
				     { Obscured },
			             };
static LogicalParms LogicalParmVec[] = { 
				     { { 0.0, 0.0, 0.0 }, GXclear, 7 },
				     { { 0.0, 0.0, 0.0 }, GXand, 7 },
				     { { 0.0, 0.0, 0.0 }, GXandReverse, 7 },
				     { { 0.0, 0.0, 0.0 }, GXcopy, 7 },
				     { { 0.0, 0.0, 0.0 }, GXandInverted, 7 },
				     { { 0.0, 0.0, 0.0 }, GXnoop, 7 },
				     { { 0.0, 0.0, 0.0 }, GXxor, 7 },
				     { { 0.0, 0.0, 0.0 }, GXor, 7 },
				     { { 0.0, 0.0, 0.0 }, GXnor, 7 },
				     { { 0.0, 0.0, 0.0 }, GXequiv, 7 },
				     { { 0.0, 0.0, 0.0 }, GXinvert, 7 },
				     { { 0.0, 0.0, 0.0 }, GXorReverse, 7 },
				     { { 0.0, 0.0, 0.0 }, GXcopyInverted, 7 },
				     { { 0.0, 0.0, 0.0 }, GXorInverted, 7 },
				     { { 0.0, 0.0, 0.0 }, GXnand, 7 },
				     { { 0.0, 0.0, 0.0 }, GXset, 7 },
			               };
static QueryParms QueryParmVec[] = { 
 					{ 0, 0, xieValDefault },
					{ 0, 0, xieValAll },
					{ 0, 0, xieValColorAlloc },
					{ 0, 0, xieValConstrain },
					{ 0, 0, xieValConvertFromRGB },
					{ 0, 0, xieValConvertToRGB },
					{ 0, 0, xieValConvolve },
					{ 0, 0, xieValDecode },
					{ 0, 0, xieValDither },
					{ 0, 0, xieValEncode },
					{ 0, 0, xieValGamut },
					{ 0, 0, xieValGeometry },
					{ 0, 0, xieValHistogram },
					{ 0, 0, xieValWhiteAdjust },
					{ 256, 256, 0 }
				   };

Test test[] = {
  {"-ColorList","XieCreateColorList/XieDestroyColorList",
		InitCreateDestroy, DoCreateDestroyColorList, NullProc, 
		EndCreateDestroy, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } }, 
  {"-LUT","XieCreateLUT/XieDestroyLUT",
		InitCreateDestroy, DoCreateDestroyLUT, NullProc, 
		EndCreateDestroy, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } }, 
  {"-Photomap","XieCreatePhotomap/XieDestroyPhotomap",
		InitCreateDestroy, DoCreateDestroyPhotomap, NullProc, 
		EndCreateDestroy, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } }, 
  {"-ROI","XieCreateROI/XieDestroyROI",
		InitCreateDestroy, DoCreateDestroyROI, NullProc, 
		EndCreateDestroy, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } }, 
  {"-Photospace","XieCreatePhotospace/XieDestroyPhotospace",
		InitCreateDestroy, DoCreateDestroyPhotospace, NullProc, 
		EndCreateDestroy, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } }, 
  {"-Photoflo","XieCreatePhotoflo/XieDestroyPhotoflo size 2",
		InitCreateDestroyPhotoflo, DoCreateDestroyPhotoflo, NullProc, 
		EndCreateDestroyPhotoflo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } }, 
  {"-QueryPhotomap","XieQueryPhotomap",
		InitQueryPhotomap, DoQueryPhotomap, NullProc, 
		EndQueryPhotomap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-QueryColorList","XieQueryColorList",
		InitQueryColorList, DoQueryColorList, NullProc, 
		EndQueryColorList, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } }, 
  {"-QueryTechniquesDefault","XieQueryTechniques Default",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 0 ] } },
  {"-QueryTechniquesAll","XieQueryTechniques All",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 1 ] } },
  {"-QueryTechniquesColorAlloc","XieQueryTechniques ColorAlloc",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 2 ] } },
  {"-QueryTechniquesConstrain","XieQueryTechniques Constrain",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 3 ] } },
  {"-QueryTechniquesConvertFromRGB","XieQueryTechniques ConvertFromRGB",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 4 ] } },
  {"-QueryTechniquesConvertToRGB","XieQueryTechniques ConvertToRGB",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 5 ] } },
  {"-QueryTechniquesConvolve","XieQueryTechniques Convolve",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 6 ] } },
  {"-QueryTechniquesDecode","XieQueryTechniques Decode",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 7 ] } },
  {"-QueryTechniquesDither","XieQueryTechniques Dither",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 8 ] } },
  {"-QueryTechniquesEncode","XieQueryTechniques Encode",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 9 ] } },
  {"-QueryTechniquesGamut","XieQueryTechniques Gamut",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 10 ] } },
  {"-QueryTechniquesGeometry","XieQueryTechniques Geometry",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 11 ] } },
  {"-QueryTechniquesHistogram","XieQueryTechniques Histogram",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 12 ] } },
  {"-QueryTechniquesWhiteAdjust","XieQueryTechniques WhiteAdjust",
		InitQueryTechniques, DoQueryTechniques, NullProc, 
		EndQueryTechniques, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL,
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 13 ] } },
  {"-QueryPhotoflo","XieQueryPhotoflo",
		InitQueryPhotoflo, DoQueryPhotoflo, NullProc, 
		EndQueryPhotoflo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) &QueryParmVec[ 14 ] } },
  {"-PurgeColorList","XiePurgeColorList",
		InitPurgeColorList, DoPurgeColorList, NullProc, 
		EndPurgeColorList, VALL, 0, 0,
		{1, SUBSET_FULL, 0, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-Abort","XieAbort",
		InitAbort, DoAbort, NullProc, 
		EndAbort, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { NULL, NULL, NULL }, 
		 ( XPointer ) &AbortParmVec[ 0 ] } },
  {"-Await","XieAwait",
		InitAwait, DoAwait, NullProc, 
		EndAwait, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { NULL, NULL, NULL },
		 ( XPointer ) &AwaitParmVec[ 0 ] } }, 
  {"-importclientlut1","ICL/EL 256 element immediate",
		InitImportClientLUT, DoImportClientLUTImmediate, NullProc, 
		EndImportClientLUT, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-importclientlut2","ICL/EL 256 element stored",
		InitImportClientLUT, DoImportClientLUTStored, NullProc, 
		EndImportClientLUT, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-importclientphoto1","ICP/EP 512x512x8 immediate",
		InitImportClientPhoto, DoImportClientPhotoImmediate, NullProc, 
		EndImportClientPhoto, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importclientphoto2","ICP/EP 512x512x8 stored",
		InitImportClientPhoto, DoImportClientPhotoStored, NullProc, 
		EndImportClientPhoto, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importclientroi1","ICR/ER 10 rectangles immediate",
		InitImportClientROI, DoImportClientROIImmediate, NullProc, 
		EndImportClientROI, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-importclientroi2","ICR/ER 10 rectangles stored",
		InitImportClientROI, DoImportClientROIStored, NullProc, 
		EndImportClientROI, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-exportclientlut1","IL/ECL 256 element immediate",
		InitImportClientLUT, DoImportClientLUTImmediate, NullProc, 
		EndImportClientLUT, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-exportclientlut2","IL/ECL 256 element stored",
		InitImportClientLUT, DoImportClientLUTStored, NullProc, 
		EndImportClientLUT, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-exportclientphoto1","IP/ECP 512x512x8 immediate",
		InitImportClientPhoto, DoImportClientPhotoImmediate, NullProc, 
		EndImportClientPhoto, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-exportclientphoto2","IP/ECP 512x512x8 stored",
		InitImportClientPhoto, DoImportClientPhotoStored, NullProc, 
		EndImportClientPhoto, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-exportclientroi1","IR/ECR 10 rectangles immediate",
		InitImportClientROI, DoImportClientROIImmediate, NullProc, 
		EndImportClientROI, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-exportclientroi2","IR/ECR 10 rectangles stored",
		InitImportClientROI, DoImportClientROIStored, NullProc, 
		EndImportClientROI, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		 { NULL, NULL, NULL }, ( XPointer ) NULL } },
  {"-importlut1","IL/EL 256 element src = dest immediate",
		InitImportLUT, DoImportLUTImmediate, NullProc, 
		EndImportLUT, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { NULL, NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importlut2","IL/EL 256 element src = dest stored",
		InitImportLUT, DoImportLUTStored, NullProc, 
		EndImportLUT, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { NULL, NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importphoto1","IP/EP 512x512x8 src = dest immediate",
		InitImportPhoto, DoImportPhotoImmediate, NullProc, 
		EndImportPhoto, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importphoto2","IP/EP 512x512x8 src = dest stored",
		InitImportPhoto, DoImportPhotoStored, NullProc, 
		EndImportPhoto, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importroi1","IR/ER 10 rectangles src = dest immediate",
		InitImportROI, DoImportROIImmediate, NullProc, 
		EndImportROI, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { NULL, NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importroi2","IR/ER 10 rectangles src = dest stored",
		InitImportROI, DoImportROIStored, NullProc, 
		EndImportROI, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { NULL, NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-importdrawable1","ID/ED 600x600x8 immediate - Pixmap src, window dest",
		InitImportDrawablePixmap, DoImportDrawablePixmapImmediate, NullProc, 
		EndImportDrawablePixmap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[0] } }, 
  {"-importdrawable2","ID/ED 600x600x8 src = dest immediate - Window",
		InitImportDrawableWindow, DoImportDrawableWindowImmediate, NullProc, 
		EndImportDrawableWindow, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[0] } }, 
  {"-importdrawable3","ID/ED 600x600x8 immediate - Window src, dest obscuring",
		InitImportDrawableWindow, DoImportDrawableWindowImmediate, NullProc, 
		EndImportDrawableWindow, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[2] } }, 
  {"-importdrawable4","ID/ED 600x600x8 immediate - Window src, dest obscured",
		InitImportDrawableWindow, DoImportDrawableWindowImmediate, NullProc, 
		EndImportDrawableWindow, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[1] } }, 
  {"-importdrawable5","IDP/EDP 600x600x8 src = dest immediate - Pixmap src",
		InitImportDrawablePixmap, DoImportDrawablePlanePixmapImmediate, NullProc, 
		EndImportDrawablePixmap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[0] } }, 
  {"-importdrawable6","IDP/EDP 600x600x8 src = dest immediate - Window src",
		InitImportDrawableWindow, DoImportDrawablePlaneWindowImmediate, 		NullProc, EndImportDrawableWindow, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[0] } }, 
  {"-importdrawable7","IDP/EDP 600x600x8 immediate - Window src, dest obscuring",
		InitImportDrawableWindow, DoImportDrawablePlaneWindowImmediate, 
		NullProc, EndImportDrawableWindow, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[2] } }, 
  {"-importdrawable8","IDP/EDP 600x600x8 immediate - Window src, dest obscured",
		InitImportDrawableWindow, DoImportDrawablePlaneWindowImmediate, 
		NullProc, EndImportDrawableWindow, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ImportParmVec[1] } }, 
  {"-simpleflo1","ICP/ED 512x512x8 immediate",
		InitSimpleFlo, DoSimpleFloImmediateData, NullProc, 
		EndSimpleFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflo2","ICP/ED 512x512x8 stored",
		InitSimpleFlo, DoSimpleFloStoredData, NullProc, 
		EndSimpleFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflo3","ICP/EP 512x512x8 immediate",
		InitSimpleFlo, DoSimpleFloImmediatePhotomap, NullProc, 
		EndSimpleFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflo4","ICP/EP 512x512x8 stored",
		InitSimpleFlo, DoSimpleFloStoredPhotomap, NullProc, 
		EndSimpleFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflo5","ICP/EP IP/ED 512x512x8 immediate",
		InitSimpleFlo, DoSimpleFloImmediatePhotomapToDrawable, NullProc,
		EndSimpleFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflo6", "ICP/EP IP/ED 512x512x8 stored",
		InitSimpleFlo, DoSimpleFloStoredPhotomapToDrawable, NullProc,
		EndSimpleFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflomap1","IP/ED 512x512x8 immediate",
		InitSimpleFloMap, DoSimpleFloMapImmediateData, NullProc,
		EndSimpleFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflomap2","IP/ED 512x512x8 stored",
		InitSimpleFloMap, DoSimpleFloMapStoredData, NullProc,
		EndSimpleFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflomap3","IP/ECP 512x512x8 immediate",
		InitSimpleFloMap, DoSimpleFloMapClientPhotoImmediateData, 
		NullProc, EndSimpleFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-simpleflomap4","IP/ECP 512x512x8 stored",
		InitSimpleFloMap, DoSimpleFloMapClientPhotoStoredData, 
		NullProc, EndSimpleFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-constrain1","Constrain HardClip IP/C/ED 512x512x8 immediate",
		InitConstrainFlo, DoConstrainFloMapImmediate, NullProc,
		EndConstrainFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ConstrainParmVec[0] } }, 
  {"-constrain2","Constrain HardClip IP/C/ED 512x512x8 stored",
		InitConstrainFlo, DoConstrainFloMapStored, NullProc,
		EndConstrainFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ConstrainParmVec[0] } }, 
  {"-constrain3","Constrain ClipScale IP/C/ED 512x512x8 immediate",
		InitConstrainFlo, DoConstrainFloMapImmediate, NullProc,
		EndConstrainFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ConstrainParmVec[1] } }, 
  {"-constrain4","Constrain ClipScale IP/C/ED 512x512x8 stored",
		InitConstrainFlo, DoConstrainFloMapStored, NullProc,
		EndConstrainFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ConstrainParmVec[2] } }, 
  {"-unconstrain1","Unconstrain/Constrain ClipScale IP/UC/C/ED 512x512x8 immediate",
		InitUnconstrainFlo, DoUnconstrainFloMapImmediate, NullProc,
		EndUnconstrainFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &UnconstrainParmVec[0] } }, 
  {"-unconstrain2","Unconstrain/Constrain ClipScale IP/UC/C/ED 512x512x8 stored",
		InitUnconstrainFlo, DoUnconstrainFloMapStored, NullProc,
		EndUnconstrainFlo, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &UnconstrainParmVec[0] } }, 
  {"-pasteup1","PasteUp IP/P/ED 512x512x8",
                InitPasteUp, DoPasteUp, NullProc,
                EndPasteUp, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &PasteUpParmVec[0] } }, 
  {"-pasteup2","PasteUp Overlapping tiles with constant fill IP/P/ED 512x512x8",
                InitPasteUp, DoPasteUp, NullProc,
                EndPasteUp, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &PasteUpParmVec[1] } }, 
  {"-geometry1","Geometry Rotate 12 degrees NearestNeighbor IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[0] } }, 
  {"-geometry2","Geometry Rotate 147 degrees NearestNeighbor IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[1] } }, 
  {"-geometry3","Geometry Rotate 193 degrees Nearest Neighbor IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[2] } }, 
  {"-geometry4","Geometry Rotate 311 degrees Nearest Neighbor IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[3] } }, 
  {"-geometry5","Geometry Mirror X Nearest Neighbor IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[4] } }, 
  {"-geometry6","Geometry Mirror Y Nearest Neighbor IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[5] } }, 
  {"-geometry7","Geometry Mirror XY NearestNeighbor IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[6] } }, 
  {"-geometry8","Crop x=256, y=256, w=256, h=256 NearestNeighbor IP/G/ED",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[7] } }, 
  {"-geometry9","Scale NearestNeighbor 128x128 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[8] } }, 
  {"-geometry10","Scale NearestNeighbor 256x256 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[9] } }, 
  {"-geometry11","Scale NearestNeighbor 256x512 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[10] } }, 
  {"-geometry12","Scale NearestNeighbor 512x128 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[11] } }, 
  {"-geometry13","Scale NearestNeighbor 256x768 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[12] } }, 
  {"-geometry14","Scale NearestNeighbor 768x128 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[13] } }, 
  {"-geometry15","Geometry Rotate 12 degrees Antialias IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[14] } }, 
  {"-geometry16","Geometry Rotate 147 degrees Antialias IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[15] } }, 
  {"-geometry17","Geometry Rotate 193 degrees Antialias IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[16] } }, 
  {"-geometry18","Geometry Rotate 311 degrees Antialias IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[17] } }, 
  {"-geometry19","Geometry Mirror X Antialias IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[18] } }, 
  {"-geometry20","Geometry Mirror Y Antialias IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[19] } }, 
  {"-geometry21","Geometry Mirror XY Antialias IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[20] } }, 
  {"-geometry22","Crop x=256, y=256, w=256, h=256 Antialias IP/G/ED",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[21] } }, 
  {"-geometry23","Scale Antialias 128x128 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[22] } }, 
  {"-geometry24","Scale Antialias 256x256 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[23] } }, 
  {"-geometry25","Scale Antialias 256x512 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[24] } }, 
  {"-geometry26","Scale Antialias 512x128 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[25] } }, 
  {"-geometry27","Scale Antialias 256x768 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[26] } }, 
  {"-geometry28","Scale Antialias 768x128 IP/G/ED 512x512x8",
                InitGeometry, DoGeometry, NullProc,
                EndGeometry, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 1 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[27] } }, 
  {"-geomg31dscale1","Geometry Scaled G31D FAX NearestNeighbor IP/G/ED 1728x1102",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 7 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[28] } }, 
  {"-geomg31dscale2","Geometry Scaled G31D FAX AntiAlias IP/G/ED 1728x1102",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 7 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[29] } }, 
  {"-geomg32dscale1","Geometry Scaled G32D FAX NearestNeighbor IP/G/ED 1728x2100",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 6 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[28] } }, 
  {"-geomg32dscale2","Geometry Scaled G32D FAX AntiAlias IP/G/ED 1728x2100",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 6 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[29] } }, 
  {"-geomg4scale1","Geometry Scaled G42D FAX NearestNeighbor IP/G/ED 2560x3300",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[30] } }, 
  {"-geomg4scale2","Geometry Scaled G42D FAX AntiAlias IP/G/ED 2560x3300",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[31] } }, 
  {"-geometryfax1","Geometry Scaled Rotate 90 degrees G42D FAX NearestNeighbor IP/G/ED 2560x3300",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[32] } }, 
  {"-geometryfax2","Geometry Scaled Rotate 147 degrees G42D FAX NearestNeighbor IP/G/ED 2560x3300x2",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[33] } }, 
  {"-geometryfax3","Geometry Scaled Rotate 193 degrees G42D FAX Nearest Neighbor IP/G/ED 2560x3300x2",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[34] } }, 
  {"-geometryfax4","Geometry Scaled Rotate 311 degrees G42D FAX Nearest Neighbor IP/G/ED 2560x3300x2",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[35] } }, 
  {"-geometryfax5","Geometry Scaled Rotate 90 degrees G42D FAX Antialias IP/G/ED 2560x3300",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[36] } }, 
  {"-geometryfax6","Geometry Scaled Rotate 147 degrees G42D FAX Antialias IP/G/ED 2560x3300x2",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[37] } }, 
  {"-geometryfax7","Geometry Scaled Rotate 193 degrees G42D FAX Antialias IP/G/ED 2560x3300x2",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[38] } }, 
  {"-geometryfax8","Geometry Scaled Rotate 311 degrees G42D FAX Antialias IP/G/ED 2560x3300x2",
                InitGeometryFAX, DoGeometryFAX, NullProc,
                EndGeometryFAX, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 4 ], NULL, NULL },
		   ( XPointer ) &GeometryParmVec[39] } }, 
  {"-dither1","Dither diffusion IP/D/C/ED 512x512x8 immediate",
		InitDitherFloMap, DoDitherFloMapImmediate, NullProc,
		EndDitherFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &DitherParmVec[ 0 ] } },
  {"-dither2","Dither diffusion IP/D/C/ED 512x512x8 stored",
		InitDitherFloMap, DoDitherFloMapStored, NullProc,
		EndDitherFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &DitherParmVec[ 0 ] } },
  {"-dither3","Dither default IP/D/C/ED 512x512x8 immediate",
		InitDitherFloMap, DoDitherFloMapImmediate, NullProc,
		EndDitherFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &DitherParmVec[ 1 ] } },
  {"-dither4","Dither default IP/D/C/ED 512x512x8 stored",
		InitDitherFloMap, DoDitherFloMapStored, NullProc,
		EndDitherFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &DitherParmVec[ 1 ] } },
  {"-dither5","Dither default IP/D/C/EDP 512x512x8 immediate",
		InitDitherFloMap, DoDitherFloMapImmediate, 
		NullProc, EndDitherFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &DitherParmVec[ 2 ] } },
  {"-dither6","Dither default IP/D/C/EDP 512x512x8 stored",
		InitDitherFloMap, DoDitherFloMapStored, 
		NullProc, EndDitherFloMap, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &DitherParmVec[ 2 ] } },
  {"-logicalmonadic1","Logical IP/L/ED Monadic Clear ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 0 ] } },
  {"-logicalmonadic2","Logical IP/L/ED Monadic And ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		  ( XPointer ) &LogicalParmVec[ 1 ] } },
  {"-logicalmonadic3","Logical IP/L/ED Monadic AndReverse ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 2 ] } },
  {"-logicalmonadic4","Logical IP/L/ED Monadic Copy ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 3 ] } },
  {"-logicalmonadic5","Logical IP/L/ED Monadic AndInverted ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 4 ] } },
  {"-logicalmonadic6","Logical IP/L/ED Monadic NoOp ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 5 ] } },
  {"-logicalmonadic7","Logical IP/L/ED Monadic Xor ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 6 ] } },
  {"-logicalmonadic8","Logical IP/L/ED Monadic Or ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 7 ] } },
  {"-logicalmonadic9","Logical IP/L/ED Monadic Nor ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 8 ] } },
  {"-logicalmonadic10","Logical IP/L/ED Monadic Equiv ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 9 ] } },
  {"-logicalmonadic11","Logical IP/L/ED Monadic Invert ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 10 ] } },
  {"-logicalmonadic12","Logical IP/L/ED Monadic OrReverse ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 11 ] } },
  {"-logicalmonadic13","Logical IP/L/ED Monadic CopyInverted ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 12 ] } },
  {"-logicalmonadic14","Logical IP/L/ED Monadic OrInverted ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 13 ] } },
  {"-logicalmonadic15","Logical IP/L/ED Monadic Nand ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 14 ] } },
  {"-logicalmonadic16","Logical IP/L/ED Monadic Set ( 0 constant ) immediate",
		InitLogicalMonadic, DoLogicalMonadicImmediate, NullProc,
		EndLogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 15 ] } },
  {"-logicaldyadic1","Logical IP/L/ED Dyadic Clear immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 0 ] } },
  {"-logicaldyadic2","Logical IP/L/ED Dyadic And immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 1 ] } },
  {"-logicaldyadic3","Logical IP/L/ED Dyadic AndReverse immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 2 ] } },
  {"-logicaldyadic4","Logical IP/L/ED Dyadic Copy immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 3 ] } },
  {"-logicaldyadic5","Logical IP/L/ED Dyadic AndInverted immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 4 ] } },
  {"-logicaldyadic6","Logical IP/L/ED Dyadic NoOp immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 5 ] } },
  {"-logicaldyadic7","Logical IP/L/ED Dyadic Xor immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 6 ] } },
  {"-logicaldyadic8","Logical IP/L/ED Dyadic Or immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 7 ] } },
  {"-logicaldyadic9","Logical IP/L/ED Dyadic Nor immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 8 ] } },
  {"-logicaldyadic10","Logical IP/L/ED Dyadic Equiv immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 9 ] } },
  {"-logicaldyadic11","Logical IP/L/ED Dyadic Invert immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 10 ] } },
  {"-logicaldyadic12","Logical IP/L/ED Dyadic OrReverse immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 11 ] } },
  {"-logicaldyadic13","Logical IP/L/ED Dyadic CopyInverted immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 12 ] } },
  {"-logicaldyadic14","Logical IP/L/ED Dyadic OrInverted immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 13 ] } },
  {"-logicaldyadic15","Logical IP/L/ED Dyadic Nand immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 14 ] } },
  {"-logicaldyadic16","Logical IP/L/ED Dyadic Set immediate",
		InitLogicalDyadic, DoLogicalDyadicImmediate, NullProc,
		EndLogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 15 ] } },
  {"-logicalmonadicroi1","ROI Logical IP/IR/L/ED Monadic Clear ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 0 ] } },
  {"-logicalmonadicroi2","ROI Logical IP/IR/L/ED Monadic And ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 1 ] } },
  {"-logicalmonadicroi3","ROI Logical IP/IR/L/ED Monadic AndReverse ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 2 ] } },
  {"-logicalmonadicroi4","ROI Logical IP/IR/L/ED Monadic Copy ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 3 ] } },
  {"-logicalmonadicroi5","ROI Logical IP/IR/L/ED Monadic AndInverted ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 4 ] } },
  {"-logicalmonadicroi6","ROI Logical IP/IR/L/ED Monadic NoOp ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 5 ] } },
  {"-logicalmonadicroi7","ROI Logical IP/IR/L/ED Monadic Xor ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 6 ] } },
  {"-logicalmonadicroi8","ROI Logical IP/IR/L/ED Monadic Or ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 7 ] } },
  {"-logicalmonadicroi9","ROI Logical IP/IR/L/ED Monadic Nor ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 8 ] } },
  {"-logicalmonadicroi10","ROI Logical IP/IR/L/ED Monadic Equiv ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 9 ] } },
  {"-logicalmonadicroi11","ROI Logical IP/IR/L/ED Monadic Invert ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 10 ] } },
  {"-logicalmonadicroi12","ROI Logical IP/IR/L/ED Monadic OrReverse ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 11 ] } },
  {"-logicalmonadicroi13","ROI Logical IP/IR/L/ED Monadic CopyInverted ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 12 ] } },
  {"-logicalmonadicroi14","ROI Logical IP/IR/L/ED Monadic OrInverted ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 13 ] } },
  {"-logicalmonadicroi15","ROI Logical IP/IR/L/ED Monadic Nand ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 14 ] } },
  {"-logicalmonadicroi16","ROI Logical IP/IR/L/ED Monadic Set ( 0 constant ) immediate",
		InitROILogicalMonadic, DoROILogicalMonadicImmediate, NullProc,
		EndROILogicalMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &LogicalParmVec[ 15 ] } },
  {"-logicaldyadicroi1","ROI Logical IP/IR/L/ED Dyadic Clear immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 0 ] } },
  {"-logicaldyadicroi2","ROI Logical IP/IR/L/ED Dyadic And immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 1 ] } },
  {"-logicaldyadicroi3","ROI Logical IP/IR/L/ED Dyadic AndReverse immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 2 ] } },
  {"-logicaldyadicroi4","ROI Logical IP/IR/L/ED Dyadic Copy immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 3 ] } },
  {"-logicaldyadicroi5","ROI Logical IP/IR/L/ED Dyadic AndInverted immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 4 ] } },
  {"-logicaldyadicroi6","ROI Logical IP/IR/L/ED Dyadic NoOp immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 5 ] } },
  {"-logicaldyadicroi7","ROI Logical IP/IR/L/ED Dyadic Xor immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 6 ] } },
  {"-logicaldyadicroi8","ROI Logical IP/IR/L/ED Dyadic Or immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 7 ] } },
  {"-logicaldyadicroi9","ROI Logical IP/IR/L/ED Dyadic Nor immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 8 ] } },
  {"-logicaldyadicroi10","ROI Logical IP/IR/L/ED Dyadic Equiv immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 9 ] } },
  {"-logicaldyadicroi11","ROI Logical IP/IR/L/ED Dyadic Invert immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 10 ] } },
  {"-logicaldyadicroi12","ROI Logical IP/IR/L/ED Dyadic OrReverse immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 11 ] } },
  {"-logicaldyadicroi13","ROI Logical IP/IR/L/ED Dyadic CopyInverted immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 12 ] } },
  {"-logicaldyadicroi14","ROI Logical IP/IR/L/ED Dyadic OrInverted immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 13 ] } },
  {"-logicaldyadicroi15","ROI Logical IP/IR/L/ED Dyadic Nand immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 14 ] } },
  {"-logicaldyadicroi16","ROI Logical IP/IR/L/ED Dyadic Set immediate",
		InitROILogicalDyadic, DoROILogicalDyadicImmediate, NullProc,
		EndROILogicalDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[1], NULL }, 
		 ( XPointer ) &LogicalParmVec[ 15 ] } },
  {"-blend1","Blend monadic src constant 0.1 alpha constant 0.5 IP/B/ED 512x512 immediate",
		InitBlendMonadic, DoBlendMonadicImmediate, NullProc,
		EndBlendMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &BlendParmVec[ 0 ] } },
  {"-blend2","Blend dyadic alpha constant 0.5 IP/IP/B/ED 512x512 immediate",
		InitBlendDyadic, DoBlendDyadicImmediate, NullProc,
		EndBlendDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[ 1 ], NULL }, 
		 ( XPointer ) &BlendParmVec[ 0 ] } },
  {"-blendroi1","Blend monadic ROI src constant 0.1 alpha constant 0.5 IP/B/ED 512x512 immediate",
		InitROIBlendMonadic, DoROIBlendMonadicImmediate, NullProc,
		EndROIBlendMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL }, 
		 ( XPointer ) &BlendParmVec[ 0 ] } },
  {"-blendroi2","Blend dyadic ROI alpha constant 0.5 IP/IP/B/ED 512x512 immediate",
		InitROIBlendDyadic, DoROIBlendDyadicImmediate, NullProc,
		EndROIBlendDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], &ImageInfo[ 1 ], NULL }, 
		 ( XPointer ) &BlendParmVec[ 0 ] } },
  {"-blendalpha1","Blend monadic src constant 220 alpha plane brains IP/IP/B/ED 512x512 immediate",
		InitBlendMonadic, DoBlendMonadicImmediate, NullProc,
		EndBlendMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		{ &ImageInfo[ 0 ], NULL, &ImageInfo[ 5 ] }, 
		 ( XPointer ) &BlendParmVec[ 1 ] } },
  {"-blendalpha2","Blend dyadic alpha plane alpha constant 250 IP/IP/IP/B/ED 512x512 immediate",
		InitBlendDyadic, DoBlendDyadicImmediate, NullProc,
		EndBlendDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		{ &ImageInfo[ 5 ], &ImageInfo[ 1 ], &ImageInfo[ 0 ] }, 
		 ( XPointer ) &BlendParmVec[ 2 ] } },
  {"-blendalpharoi1","Blend monadic ROI src constant 220 alpha plane brains IP/B/ED 512x512 immediate",
		InitROIBlendMonadic, DoROIBlendMonadicImmediate, NullProc,
		EndROIBlendMonadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		{ &ImageInfo[ 2 ], NULL, &ImageInfo[ 5 ] }, 
		 ( XPointer ) &BlendParmVec[ 1 ] } },
  {"-blendalpharoi2","Blend dyadic ROI alpha plane alpha constant 250 lena IP/IP/IP/B/ED 512x512 immediate",
		InitROIBlendDyadic, DoROIBlendDyadicImmediate, NullProc,
		EndROIBlendDyadic, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, 
		{ &ImageInfo[ 2 ], &ImageInfo[ 0 ], &ImageInfo[ 1 ] }, 
		 ( XPointer ) &BlendParmVec[ 2 ] } },
  {"-point1","Point IP/IL/P/ED 512x512 8 to 8 immediate",
		InitPoint, DoPointImmediate, NullProc,
		EndPoint, VALL, 0, 0,
		{1, SUBSET_FULL | CAPA_COLOR_8, 2048, NULL, 
		 { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &PointParmVec[ 0 ] } }, 
  {"-point2","Point IP/IL/P/ED 512x512 8 to 8 stored",
		InitPoint, DoPointStored, NullProc,
		EndPoint, VALL, 0, 0,
		{1, SUBSET_FULL | CAPA_COLOR_8, 2048, NULL, 
		 { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &PointParmVec[ 0 ] } }, 
  {"-point3","Point IP/IL/P/ED 512x512 1 to 8 immediate",
		InitPoint, DoPointImmediate, NullProc,
		EndPoint, VALL, 0, 0,
		{1, SUBSET_FULL | CAPA_COLOR_8, 2048, NULL, 
		 { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &PointParmVec[ 1 ] } }, 
  {"-point4","Point IP/IL/P/ED 512x512 1 to 8 stored",
		InitPoint, DoPointStored, NullProc,
		EndPoint, VALL, 0, 0,
		{1, SUBSET_FULL | CAPA_COLOR_8, 2048, NULL, 
		 { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &PointParmVec[ 1 ] } }, 
  {"-point5","Point IP/IL/P/EDP 512x512 8 to 1 immediate",
		InitPoint, DoPointImmediate, NullProc,
		EndPoint, VALL, 0, 0,
		{1, SUBSET_FULL | CAPA_COLOR_8, 2048, NULL, 
		 { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &PointParmVec[ 2 ] } }, 
  {"-point6","Point IP/IL/P/EDP 512x512 8 to 1 stored",
		InitPoint, DoPointStored, NullProc,
		EndPoint, VALL, 0, 0,
		{1, SUBSET_FULL | CAPA_COLOR_8, 2048, NULL, 
		 { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &PointParmVec[ 2 ] } }, 
  {"-redefine","RedefinePhotoflo",
		InitRedefine, DoRedefine, NullProc,
		EndRedefine, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &RedefineParmVec[ 0 ] } }, 
  {"-modify1","ModifyPhotoflo change ROI offsets and size",
		InitModifyROI, DoModifyROI, NullProc,
		EndModifyROI, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) &ModifyParmVec[ 0 ] } }, 
  {"-modify2","ModifyPhotoflo change point element LUT",
		InitModifyPoint, DoModifyPoint, NullProc,
		EndModifyPoint, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-modify3","ModifyPhotoflo change export drawable x,y location",
		InitModifySimple, DoModifySimple, NullProc,
		EndModifySimple, VALL, 0, 0,
		{1, SUBSET_FULL, 2048, NULL, { &ImageInfo[ 0 ], NULL, NULL },
		   ( XPointer ) NULL } }, 
  {"-converttoindex","Convert to index CTI/ED",
		InitConvertToIndex, DoConvertToIndex, NullProc,
		EndConvertToIndex, VALL, 0, 0,
		{1, SUBSET_FULL | CAPA_COLOR_8, 2048, NULL, 
		 { &ImageInfo[ 3 ], NULL, NULL }, 
		( XPointer ) &CvtToIndexParmVec[ 0 ] } }, 
  {NULL,NULL, NULL, NULL, NULL, NULL, 0, 0, 0,
		{1, 0, 0, NULL, { NULL, NULL, NULL }, 
		 NULL } },
};
