.TH XLSFONTS 1 "1 March 1988" "X Version 11"
.SH NAME
xlsfonts - X window system font list displayer
.SH SYNOPSIS
.B xlsfonts
[-options ...] [pattern]
.SH DESCRIPTION
.I Xlsfonts
displays all fonts on a given display which match the given \fIpattern\fP.
Patterns may include "*" to match any sequence of characters (including
the null sequence) and
"?" to match any single character.  If no pattern is given, "*" is assumed.
.PP
The wildcard characters "*" and "?" should be quoted to prevent them from
being expanded by the shell.
.SH "OPTIONS"
.PP
.TP 8
.B \-display \fIhost\fP:\fIdpy\fP
Normally,
.I xlsfonts
gets the host and display number to use from the environment
variable ``DISPLAY''.  One can, however specify them explicitly.
The
.I host
specifies which machine to query for the list of fontnames and
the
.I dpy
argument specifies the display number.
For example,
``xlsfonts -display expo:1'' queries display one on the machine expo.
.PP
.PP
.TP 8
.B \-l
Give a long listing for each font.
.TP 8
.B \-m
When used with \fB\-l\fP the minimum and maximum bounds are printed.
.TP 8
.B \-C
Generate a multiple column listing.
.TP 8
.B \-1
Generate a single column listing.
.PP
.SH "SEE ALSO"
X(1), X(8C), xterm(1), xfd(1)
.SH ENVIRONMENT
.TP 8
.B DISPLAY
to get the default host and display to use.
.SH BUGS
Accidentally doing ``xlsfonts -l'' can tie up your server for a very long time.
.SH AUTHOR
Copyright 1987 Massachusetts Institute of Technology.
.br
Mark Lillibridge, MIT Project Athena
