.TH XLSFONTS 1 "1 March 1988" "X Version 11"
.SH NAME
xlsfonts - X window system font list displayer
.SH SYNOPSIS
.B xlsfonts
[-options ...] [pattern]
.SH DESCRIPTION
.I Xlsfonts
lists the fonts that match the given \fIpattern\fP.
Patterns may include "*" to match any sequence of characters (including
no characters) and
"?" to match any single character.  If no pattern is given, "*" is assumed.
.PP
The wildcard characters "*" and "?" should be quoted to prevent them from
being expanded by the shell.
.SH "OPTIONS"
.PP
.TP 8
.B \-display \fIhost\fP:\fIdpy\fP
This option specifies the X server to contact.
.PP
.TP 8
.B \-l
This option indicates that a long listing should be generated for each font.
.TP 8
.B \-m
This option indicates that long listings should also print the minimum and
maximum bounds of each font.
.TP 8
.B \-C
This option indicates that listings should use multiple columns.
.TP 8
.B \-1
This option indicates that listings should use a single column.
.PP
.SH "SEE ALSO"
X(1), Xserver(8C), xterm(1), xfd(1)
.SH ENVIRONMENT
.TP 8
.B DISPLAY
to get the default host and display to use.
.SH BUGS
Accidentally doing ``xlsfonts -l'' can tie up your server for a very long time.
.SH COPYRIGHT
Copyright 1988, Massachusetts Institute of Technology.
.br
See \fIX(1)\fP for a full statement of rights and permissions.
.SH AUTHOR
Mark Lillibridge, MIT Project Athena
