.\" $XConsortium: iceauth.man,v 1.9 91/12/16 20:30:02 gildea Exp $
.TH ICEAUTH 1 "Release 5" "X Version 11"
.SH NAME
iceauth \- ICE authority file utility
.SH SYNOPSIS
.B iceauth
[ \fB\-f\fP \fIauthfile\fP ] [ \fB\-vqib\fP ] [ \fIcommand arg ...\fP ]
.SH DESCRIPTION
.PP
The \fIiceauth\fP program is used to edit and display the authorization 
information used in connecting with ICE.  This program is usually
used to extract authorization records from one machine and merge them in on 
another (as is the case when using remote logins or granting access to
other users).  Commands (described below) may be entered interactively,
on the \fIiceauth\fP command line, or in scripts.
.SH COPYRIGHT
Copyright 1994, X Consortium, Inc.
.SH AUTHOR
Ralph Mor, X Consortium
