/***********************************************************
Copyright 1987 by Digital Equipment Corporation, Maynard, Massachusetts,
and the Massachusetts Institute of Technology, Cambridge, Massachusetts.

                        All Rights Reserved

Permission to use, copy, modify, and distribute this software and its 
documentation for any purpose and without fee is hereby granted, 
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in 
supporting documentation, and that the names of Digital or MIT not be
used in advertising or publicity pertaining to distribution of the
software without specific, written prior permission.  

DIGITAL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
DIGITAL BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

******************************************************************/
/* $Header: tables.c,v 1.12 87/07/17 16:58:51 todd Exp $ */

extern int    ProcBadRequest(), ProcCreateWindow(),
    ProcChangeWindowAttributes(), ProcGetWindowAttributes(),
    ProcDestroyWindow(), ProcDestroySubwindows(), ProcChangeSaveSet(),
    ProcReparentWindow(), ProcMapWindow(), ProcMapSubwindows(),
    ProcUnmapWindow(), ProcUnmapSubwindows(), ProcConfigureWindow(),
    ProcCirculateWindow(), ProcGetGeometry(), ProcQueryTree(),
    ProcInternAtom(), ProcGetAtomName(), ProcChangeProperty(),
    ProcDeleteProperty(), ProcGetProperty(), ProcListProperties(),
    ProcSetSelectionOwner(), ProcGetSelectionOwner(), ProcConvertSelection(),
    ProcSendEvent(), ProcGrabPointer(), ProcUngrabPointer(),
    ProcGrabButton(), ProcUngrabButton(), ProcChangeActivePointerGrab(),
    ProcGrabKeyboard(), ProcUngrabKeyboard(), ProcGrabKey(),
    ProcUngrabKey(), ProcAllowEvents(), ProcGrabServer(),
    ProcUngrabServer(), ProcQueryPointer(), ProcGetMotionEvents(),
    ProcTranslateCoords(), ProcWarpPointer(), ProcSetInputFocus(),
    ProcGetInputFocus(), ProcQueryKeymap(), ProcOpenFont(),
    ProcCloseFont(), ProcQueryFont(), ProcQueryTextExtents(),
    ProcListFonts(), ProcListFontsWithInfo(), ProcSetFontPath(),
    ProcGetFontPath(), ProcCreatePixmap(), ProcFreePixmap(),
    ProcCreateGC(), ProcChangeGC(), ProcCopyGC(),
    ProcSetDashes(), ProcSetClipRectangles(), ProcFreeGC(),
    ProcClearToBackground(), ProcCopyArea(), ProcCopyPlane(),
    ProcPolyPoint(), ProcPolyLine(), ProcPolySegment(),
    ProcPolyRectangle(), ProcPolyArc(), ProcFillPoly(),
    ProcPolyFillRectangle(), ProcPolyFillArc(), ProcPutImage(),
    ProcGetImage(), ProcPolyText(),
    ProcImageText(), ProcCreateColormap(),
    ProcFreeColormap(), ProcCopyColormapAndFree(), ProcInstallColormap(),
    ProcUninstallColormap(), ProcListInstalledColormaps(), ProcAllocColor(),
    ProcAllocNamedColor(), ProcAllocColorCells(), ProcAllocColorPlanes(),
    ProcFreeColors(), ProcStoreColors(), ProcStoreNamedColor(),
    ProcQueryColors(), ProcLookupColor(), ProcCreateCursor(),
    ProcCreateGlyphCursor(), ProcFreeCursor(), ProcRecolorCursor(),
    ProcQueryBestSize(), ProcQueryExtension(), ProcListExtensions(),
    ProcChangeKeyboardMapping(), ProcSetPointerMapping(),
    ProcGetKeyboardMapping(), ProcGetPointerMapping(),
    ProcChangeKeyboardControl(),
    ProcGetKeyboardControl(), ProcBell(), ProcChangePointerControl(),
    ProcGetPointerControl(), ProcSetScreenSaver(), ProcGetScreenSaver(),
    ProcChangeHosts(), ProcListHosts(), ProcChangeAccessControl(),
    ProcChangeCloseDownMode(), ProcKillClient(),
    ProcRotateProperties(), ProcForceScreenSaver(),
    ProcSetModifierMapping(), ProcGetModifierMapping(),
    ProcNoOperation();

extern int    SProcSProcBadRequest(), SProcCreateWindow(),
    SProcChangeWindowAttributes(), 
    SProcDestroyWindow(), SProcDestroySubwindows(), SProcChangeSaveSet(),
    SProcReparentWindow(), SProcMapWindow(), SProcMapSubwindows(),
    SProcUnmapWindow(), SProcUnmapSubwindows(), SProcConfigureWindow(),
    SProcCirculateWindow(), SProcGetGeometry(), SProcQueryTree(),
    SProcInternAtom(), SProcGetAtomName(), SProcChangeProperty(),
    SProcDeleteProperty(), SProcGetProperty(), SProcListProperties(),
    SProcSetSelectionOwner(), SProcGetSelectionOwner(),
    SProcConvertSelection(),
    SProcSendEvent(), SProcGrabPointer(), SProcUngrabPointer(),
    SProcGrabButton(), SProcUngrabButton(), SProcChangeActivePointerGrab(),
    SProcGrabKeyboard(), SProcUngrabKeyboard(), SProcGrabKey(),
    SProcUngrabKey(), SProcAllowEvents(), SProcGrabServer(),
    SProcUngrabServer(), SProcQueryPointer(), SProcGetMotionEvents(),
    SProcTranslateCoords(), SProcWarpPointer(), SProcSetInputFocus(),
    SProcGetInputFocus(), SProcQueryKeymap(), SProcOpenFont(),
    SProcCloseFont(), SProcQueryFont(), SProcQueryTextExtents(),
    SProcListFonts(), SProcListFontsWithInfo(), SProcSetFontPath(),
    SProcGetFontPath(), SProcCreatePixmap(), SProcFreePixmap(),
    SProcCreateGC(), SProcChangeGC(), SProcCopyGC(),
    SProcSetDashes(), SProcSetClipRectangles(), SProcFreeGC(),
    SProcClearToBackground(), SProcCopyArea(), SProcCopyPlane(),
    SProcPolyPoint(), SProcPolyLine(), SProcPolySegment(),
    SProcPolyRectangle(), SProcPolyArc(), SProcFillPoly(),
    SProcPolyFillRectangle(), SProcPolyFillArc(), SProcPutImage(),
    SProcGetImage(), SProcPolyText(), 
    SProcImageText(), SProcCreateColormap(),
    SProcFreeColormap(), SProcCopyColormapAndFree(), SProcInstallColormap(),
    SProcUninstallColormap(), SProcListInstalledColormaps(), SProcAllocColor(),
    SProcAllocNamedColor(), SProcAllocColorCells(), SProcAllocColorPlanes(),
    SProcFreeColors(), SProcStoreColors(), SProcStoreNamedColor(),
    SProcQueryColors(), SProcLookupColor(), SProcCreateCursor(),
    SProcCreateGlyphCursor(), SProcFreeCursor(), SProcRecolorCursor(),
    SProcQueryBestSize(), SProcQueryExtension(), SProcListExtensions(),
    SProcChangeKeyboardMapping(), SProcSetPointerMapping(),
    SProcGetKeyboardMapping(), SProcGetPointerMapping(),
    SProcChangeKeyboardControl(),
    SProcGetKeyboardControl(), SProcBell(), SProcChangePointerControl(),
    SProcGetPointerControl(), SProcSetScreenSaver(), SProcGetScreenSaver(),
    SProcChangeHosts(), SProcListHosts(), SProcChangeAccessControl(),
    SProcChangeCloseDownMode(), SProcKillClient(), 
    SProcRotateProperties(), SProcForceScreenSaver(),
    SProcSetModifierMapping(), SProcGetModifierMapping(),
    SProcNoOperation(), SProcResourceReq();

extern void 
    SErrorEvent(), NotImplemented(), SKeyButtonPtrEvent(), SKeyButtonPtrEvent(),
    SKeyButtonPtrEvent(), SKeyButtonPtrEvent(), SKeyButtonPtrEvent(),
    SEnterLeaveEvent(), SEnterLeaveEvent(), SFocusEvent(),
    SFocusEvent(), SKeymapNotifyEvent(), SExposeEvent(),
    SGraphicsExposureEvent(), SNoExposureEvent(), SVisibilityEvent(),
    SCreateNotifyEvent(), SDestroyNotifyEvent(), SUnmapNotifyEvent(),
    SMapNotifyEvent(), SMapRequestEvent(), SReparentEvent(),
    SConfigureNotifyEvent(), SConfigureRequestEvent(), SGravityEvent(),
    SResizeRequestEvent(), SCirculateEvent(), SCirculateEvent(),
    SPropertyEvent(), SSelectionClearEvent(), SSelectionRequestEvent(),
    SSelectionNotifyEvent(), SColormapEvent(), SClientMessageEvent();

extern void
    SBadRequestReply(), NotImplemented(),
    SGetWindowAttributesReply(), SGetGeometryReply(), SQueryTreeReply(),
    SInternAtomReply(), SGetAtomNameReply(), SGetPropertyReply(),
    SListPropertiesReply(), 
    SGetSelectionOwnerReply(), SGrabPointerReply(), SGrabKeyboardReply(),
    SQueryPointerReply(), SGetMotionEventsReply(), STranslateCoordsReply(),
    SGetInputFocusReply(), SQueryKeymapReply(), SQueryFontReply(),
    SQueryTextExtentsReply(), SListFontsReply(), SListFontsWithInfoReply(),
    SGetFontPathReply(), SGetImageReply(), SListInstalledColormapsReply(),
    SAllocColorReply(), SAllocNamedColorReply(), SAllocColorCellsReply(),
    SAllocColorPlanesReply(), SQueryColorsReply(), SLookupColorReply(),
    SQueryBestSizeReply(), SQueryExtensionReply(), SListExtensionsReply(),
    SGetKeyboardMappingReply(), SGetPointerMappingReply(),
    SGetKeyboardControlReply(), SGetPointerControlReply(),
    SSetModifierMappingReply(), SGetModifierMappingReply(),
    SGetScreenSaverReply(), SListHostsReply();

int (* ProcVector[256]) () =
{
    ProcBadRequest,
    ProcCreateWindow,
    ProcChangeWindowAttributes,
    ProcGetWindowAttributes,
    ProcDestroyWindow,
    ProcDestroySubwindows,
    ProcChangeSaveSet,
    ProcReparentWindow,
    ProcMapWindow,
    ProcMapSubwindows,
    ProcUnmapWindow,
    ProcUnmapSubwindows,
    ProcConfigureWindow,
    ProcCirculateWindow,
    ProcGetGeometry,
    ProcQueryTree,
    ProcInternAtom,
    ProcGetAtomName,
    ProcChangeProperty,
    ProcDeleteProperty,
    ProcGetProperty,
    ProcListProperties,
    ProcSetSelectionOwner,
    ProcGetSelectionOwner,
    ProcConvertSelection,
    ProcSendEvent,
    ProcGrabPointer,
    ProcUngrabPointer,
    ProcGrabButton,
    ProcUngrabButton,
    ProcChangeActivePointerGrab,
    ProcGrabKeyboard,
    ProcUngrabKeyboard,
    ProcGrabKey,
    ProcUngrabKey,
    ProcAllowEvents,
    ProcGrabServer,
    ProcUngrabServer,
    ProcQueryPointer,
    ProcGetMotionEvents,
    ProcTranslateCoords,
    ProcWarpPointer,
    ProcSetInputFocus,
    ProcGetInputFocus,
    ProcQueryKeymap,
    ProcOpenFont,
    ProcCloseFont,
    ProcQueryFont,
    ProcQueryTextExtents,
    ProcListFonts,
    ProcListFontsWithInfo,
    ProcSetFontPath,
    ProcGetFontPath,
    ProcCreatePixmap,
    ProcFreePixmap,
    ProcCreateGC,
    ProcChangeGC,
    ProcCopyGC,
    ProcSetDashes,
    ProcSetClipRectangles,
    ProcFreeGC,
    ProcClearToBackground,
    ProcCopyArea,
    ProcCopyPlane,
    ProcPolyPoint,
    ProcPolyLine,
    ProcPolySegment,
    ProcPolyRectangle,
    ProcPolyArc,
    ProcFillPoly,
    ProcPolyFillRectangle,
    ProcPolyFillArc,
    ProcPutImage,
    ProcGetImage,
    ProcPolyText,
    ProcPolyText,
    ProcImageText,
    ProcImageText,
    ProcCreateColormap,
    ProcFreeColormap,
    ProcCopyColormapAndFree,
    ProcInstallColormap,
    ProcUninstallColormap,
    ProcListInstalledColormaps,
    ProcAllocColor,
    ProcAllocNamedColor,
    ProcAllocColorCells,
    ProcAllocColorPlanes,
    ProcFreeColors,
    ProcStoreColors,
    ProcStoreNamedColor,
    ProcQueryColors,
    ProcLookupColor,
    ProcCreateCursor,
    ProcCreateGlyphCursor,
    ProcFreeCursor,
    ProcRecolorCursor,
    ProcQueryBestSize,
    ProcQueryExtension,
    ProcListExtensions,
    ProcChangeKeyboardMapping,
    ProcGetKeyboardMapping,
    ProcChangeKeyboardControl,
    ProcGetKeyboardControl,
    ProcBell,
    ProcChangePointerControl,
    ProcGetPointerControl,
    ProcSetScreenSaver,
    ProcGetScreenSaver,
    ProcChangeHosts,
    ProcListHosts,
    ProcChangeAccessControl,
    ProcChangeCloseDownMode,
    ProcKillClient,
    ProcRotateProperties,
    ProcForceScreenSaver,
    ProcSetPointerMapping,
    ProcGetPointerMapping,
    ProcSetModifierMapping,
    ProcGetModifierMapping,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    ProcNoOperation    
};

int (* SwappedProcVector[256]) () =
{
    ProcBadRequest,
    SProcCreateWindow,
    SProcChangeWindowAttributes,
    SProcResourceReq,			/* GetWindowAttributes */
    SProcResourceReq,			/* 5, DestroyWindow */
    SProcResourceReq,			/* DestroySubwindows */
    SProcChangeSaveSet,
    SProcReparentWindow,
    SProcResourceReq,			/* MapWindow */
    SProcResourceReq,			/* 10 MapSubwindows */
    SProcResourceReq,			/* UnmapWindow */
    SProcResourceReq,			/* UnmapSubwindows */
    SProcConfigureWindow,
    SProcCirculateWindow,
    SProcResourceReq,			/* 15 GetGeometry */
    SProcResourceReq,			/* QueryTree */
    SProcInternAtom,
    SProcResourceReq,			/* SProcGetAtomName, */
    SProcChangeProperty,
    SProcDeleteProperty,		/* 20 */
    SProcGetProperty,
    SProcResourceReq,			/* SProcListProperties, */
    SProcSetSelectionOwner,
    SProcResourceReq, 			/* SProcGetSelectionOwner, */
    SProcConvertSelection,		/* 25 */
    SProcSendEvent,
    SProcGrabPointer,
    SProcResourceReq, 			/* SProcUngrabPointer, */
    SProcGrabButton,
    SProcUngrabButton,			/* 30 */
    SProcChangeActivePointerGrab,
    SProcGrabKeyboard,
    SProcResourceReq,			/* SProcUngrabKeyboard, */
    SProcGrabKey,
    SProcUngrabKey,			/* 35 */
    SProcAllowEvents,
    SProcResourceReq,			/* SProcGrabServer, */
    SProcResourceReq,			/* SProcUngrabServer, */
    SProcResourceReq,			/* SProcQueryPointer, */
    SProcGetMotionEvents,		/*40 */
    SProcTranslateCoords,
    SProcWarpPointer,
    SProcSetInputFocus,
    SProcGetInputFocus,
    SProcQueryKeymap,			/* 45 */
    SProcOpenFont,
    SProcResourceReq,			/* SProcCloseFont, */
    SProcResourceReq, 			/* SProcQueryFont, */
    SProcQueryTextExtents, 
    SProcListFonts,			/* 50 */
    SProcListFontsWithInfo,
    SProcSetFontPath,
    SProcGetFontPath,
    SProcCreatePixmap,
    SProcResourceReq,			/* SProcFreePixmap, */
    SProcCreateGC,
    SProcChangeGC,
    SProcCopyGC,
    SProcSetDashes,
    SProcSetClipRectangles,
    SProcResourceReq,			/* SProcFreeGC, */
    SProcClearToBackground,
    SProcCopyArea,
    SProcCopyPlane,
    SProcPolyPoint,
    SProcPolyLine,
    SProcPolySegment,
    SProcPolyRectangle,
    SProcPolyArc,
    SProcFillPoly,
    SProcPolyFillRectangle,
    SProcPolyFillArc,
    SProcPutImage,
    SProcGetImage,
    SProcPolyText,
    SProcPolyText,
    SProcImageText,
    SProcImageText,
    SProcCreateColormap,
    SProcResourceReq,			/* SProcFreeColormap, */
    SProcCopyColormapAndFree,
    SProcResourceReq,			/* SProcInstallColormap, */
    SProcResourceReq,			/* SProcUninstallColormap, */
    SProcResourceReq, 			/* SProcListInstalledColormaps,
    SProcAllocColor,
    SProcAllocNamedColor,
    SProcAllocColorCells,
    SProcAllocColorPlanes,
    SProcFreeColors,
    SProcStoreColors,
    SProcStoreNamedColor,
    SProcQueryColors,
    SProcLookupColor,
    SProcCreateCursor,
    SProcCreateGlyphCursor,
    SProcResourceReq,			/* SProcFreeCursor, */
    SProcRecolorCursor,
    SProcQueryBestSize,
    SProcQueryExtension,
    SProcListExtensions,
    SProcChangeKeyboardMapping,
    SProcGetKeyboardMapping,
    SProcChangeKeyboardControl,
    SProcGetKeyboardControl,
    SProcBell,
    SProcChangePointerControl,
    SProcGetPointerControl,
    SProcSetScreenSaver,
    SProcGetScreenSaver,
    SProcChangeHosts,
    SProcListHosts,
    SProcResourceReq,			/* SProcChangeAccessControl, */
    SProcResourceReq,			/* SProcChangeCloseDownMode, */
    SProcResourceReq,			/* SProcKillClient, */
    SProcRotateProperties,
    SProcForceScreenSaver,
    SProcSetPointerMapping,
    SProcGetPointerMapping,
    SProcSetModifierMapping,
    SProcGetModifierMapping,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    SProcNoOperation
};

void (* EventSwapVector[128]) () =
{
    SErrorEvent,
    NotImplemented,
    SKeyButtonPtrEvent,
    SKeyButtonPtrEvent,
    SKeyButtonPtrEvent,
    SKeyButtonPtrEvent,
    SKeyButtonPtrEvent,
    SEnterLeaveEvent,
    SEnterLeaveEvent,
    SFocusEvent,
    SFocusEvent,
    SKeymapNotifyEvent,
    SExposeEvent,
    SGraphicsExposureEvent,
    SNoExposureEvent,
    SVisibilityEvent,
    SCreateNotifyEvent,
    SDestroyNotifyEvent,
    SUnmapNotifyEvent,
    SMapNotifyEvent,
    SMapRequestEvent,
    SReparentEvent,
    SConfigureNotifyEvent,
    SConfigureRequestEvent,
    SGravityEvent,
    SResizeRequestEvent,
    SCirculateEvent,
    SCirculateEvent,
    SPropertyEvent,
    SSelectionClearEvent,
    SSelectionRequestEvent,
    SSelectionNotifyEvent,
    SColormapEvent,
    SClientMessageEvent
};


void (* ReplySwapVector[256]) () =
{
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SGetWindowAttributesReply,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SGetGeometryReply,
    SQueryTreeReply,
    SInternAtomReply,
    SGetAtomNameReply,
    NotImplemented,
    NotImplemented,
    SGetPropertyReply,
    SListPropertiesReply,
    NotImplemented,
    SGetSelectionOwnerReply,
    NotImplemented,
    NotImplemented,
    SGrabPointerReply,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SGrabKeyboardReply,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SQueryPointerReply,
    SGetMotionEventsReply,
    STranslateCoordsReply,
    NotImplemented,
    NotImplemented,
    SGetInputFocusReply,
    SQueryKeymapReply,
    NotImplemented,
    NotImplemented,
    SQueryFontReply,
    SQueryTextExtentsReply,
    SListFontsReply,
    SListFontsWithInfoReply,
    NotImplemented,
    SGetFontPathReply,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SGetImageReply,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SListInstalledColormapsReply,
    SAllocColorReply,
    SAllocNamedColorReply,
    SAllocColorCellsReply,
    SAllocColorPlanesReply,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SQueryColorsReply,
    SLookupColorReply,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    NotImplemented,
    SQueryBestSizeReply,
    SQueryExtensionReply,
    SListExtensionsReply,
    SGetKeyboardMappingReply,
    NotImplemented,
    SGetKeyboardControlReply,
    NotImplemented,
    NotImplemented,
    SGetPointerControlReply,
    NotImplemented,
    SGetScreenSaverReply,
    NotImplemented,
    SListHostsReply,
    NotImplemented,		/* ChangeAccessControl */
    NotImplemented,		/* ChangeCloseDownMode */
    NotImplemented,		/* KillClient */
    NotImplemented,		/* RotateProperties */
    NotImplemented,		/* ForceScreenSaver */
    NotImplemented,
    SGetPointerMappingReply,
    NotImplemented,		/* 118 */
    SGetModifierMappingReply,	/* 119 */
    NotImplemented,		/* 120 */
    NotImplemented,		/* 121 */
    NotImplemented,		/* 122 */
    NotImplemented,		/* 123 */
    NotImplemented,		/* 124 */
    NotImplemented,		/* 125 */
    NotImplemented,		/* 126 */
    NotImplemented,		/* NoOperation */
    NotImplemented
};
