.TH XMAN 1 "24 October 1988" "X Version 11"
.SH NAME
xman - display manual pages
.SH SYNOPSIS
.B xman
[-options ...]
.SH DESCRIPTION
.I Xman
is a manual page browser.  The default size of the initial \fIxman\fP
window is small so that you can leave it running throughout your entire login
session.  In the initial window there are three options:
\fIHelp\fP will pop up a window with on-line help, \fIQuit\fP will
exit, and \fIManual Page\fP will pop up a window with a manual page
browser in it.  You may pop up more than one manual page browser window
from a single execution of \fIxman\fP.
.PP
For further information on using \fIxman\fP please read the on-line
help information.  The rest of this manual page will discuss
customization of \fIxman\fP.
.PP
.I Xman
accomodates new manual sections by the use of the environment variable
MANPATH and by directory description files named \fImandesc\fP.
.I Xman
will search each directory specified in the environment variable
MANPATH for the following subdirectories only: man0, man1, ..., man8,
manl (local), and mann (new).
(It usually ignores the
information in man0 unless there is a \fImandesc\fP file that specifically
tells it not to.)
These subdirectories each represent
a separate section of the manual.  These subdirectories should contain 
man pages.  Any manual section can be renamed by an optional
\fImandesc\fP file.
.PP
As an example, if MANPATH was set to \fI/usr/man:/usr/sipb/man\fP
and there was no \fImandesc\fP file in /usr/man, \fIxman\fP
would put all of the files in the default section names
(e.g. manl gets a section name of local).
But if there were a \fImandesc\fP file in
/usr/sipb/man which contained the line \fIlSIPB Programs\fP,
then \fIxman\fP would put all files in the
manl subdirectory in a new section
called ``SIPB Programs''.  \fIXman\fP will search the \fImandesc\fP file until
there are no more lines of information.  This flexibility is ideal
for courses that have their own manual pages. 
.PP
.I Xman
creates temporary files in /tmp for all unformatted man pages and all apropos
searches.
.PP
.SH "COMMAND LINE OPTIONS"
.PP
.IP "\fB-helpfile\fP \fIfilename\fP"
Specifies a helpfile to use other than the default.
.IP \fB-bothshown\fP
Allows both the manual page and manual directory to be on the screen at
the same time.
.IP \fB-notopbox\fP
Starts without the Top Menu with the three buttons in it.
.IP "\fB-geometry\fP \fIWxH+X+Y\fP"
Sets the size and location of the Top Menu with the three buttons in it.
.IP "\fB-pagesize\fP \fIWxH+X+Y\fP"
Sets the size and location of all the Manual Pages.
.IP "\fB-bw\fP \fIpixels\fP or \fB-borderwidth\fP \fIpixels\fP"
Specifies the width of the border for all windows in \fIxman\fP.
.IP "\fB-bd\fP \fIcolor\fP or \fB-bordercolor\fP \fIcolor\fP"
Specifies the color of the borders of all windows in \fIxman\fP.
.IP "\fB-fg\fP \fIcolor\fP or \fB-foreground\fP \fIcolor\fP"
Specifies the foreground color to be used.
.IP "\fB-bg\fP \fIcolor\fP or \fB-background\fP \fIcolor\fP"
Specifies the background color to be used.
.IP "\fB-fn\fP \fIfont\fP or \fB-font\fP \fIfont\fP"
Specifies the font to use for all buttons and labels.
.IP "\fB-display\fP \fIhost:display[.screen]\fP"
Specifies a display other than the default specified by the DISPLAY
environment variable.
.IP "\fB-name\fP \fIname\fP"
Specifies the name to use when retrieving resources.
.IP "\fB-title\fP \fItitle\fP"
Specifies the title of this application.
.IP "\fB-xrm\fP \fIresources\fP"
Allows a resource to be specified on the command line.
.PP
.SH "X DEFAULTS"

The \fIxman\fP program uses the following X resources: 
\fBforeground\fP,
\fBbackground\fP,
\fBwidth\fP, \fBheight\fP,
\fBborderWidth\fP, and
\fBborderColor\fP.
.PP
In order to change the default values for widget resources you need
to know widget names.  Below are the names of some of the
most common widgets.
You can also reference Widgets by class.  The most common classes
are \fBLabel\fP, \fBCommand\fP, and \fBText\fP.
.TP 16
\fBtopBox\fP
the top menu
.TP 16
\fBhelp\fP
the help window
.TP 16
\fBmanualBrowser\fP
the manual page display window
.TP 16
\fBxmanCommands\fP
manual page command popup menu 	
.TP 16
\fBxmanSections\fP
manual page section popup menu 	
.TP 16
\fBxmanSearch\fP
manual page search popup menu
.PP
In addition, \fIxman\fP has application-specific resources which allow
unique \fIxman\fP customizations.
.PP
.TP 18
\fBmanualFontNormal\fP
The font to use for normal text in the manual pages.
.TP 18
\fBmanualFontBold\fP
The font to use for bold text in the manual pages.
.TP 18
\fBmanualFontItalic\fP
The font to use for italic text in the manual pages.
.TP 18
\fBdirectoryFontNormal\fP
The font to use for the directory text.
.TP 18
\fBbothShown\fP
Either 'true' or 'false', specifies whether or not you want both the
directory and the manual page shown at start up.
.TP 18
\fBdirectoryHeight\fP
The height in pixels of the directory, when the directory and the manual page
are shown simultaneously.
.TP 18
\fBtopCursor\fP
The cursor to use in the top box.
.TP 18
\fBhelpCursor\fP
The cursor to use in the help window.
.TP 18
\fBmanpageCursor\fP
The cursor to use in the manual page window.
.TP 18
\fBsearchEntryCursor\fP
The cursor to use in the search entry text widget.
.TP 18 
\fBhelpFile\fP
Use this rather than the system default helpfile.
.TP 18
\fBtopBox\fP
Either 'true' or 'false', determines whether the top box (containing
the help, quit and manual page buttons) or a manual page is put on the screen
at start-up.  The default is true.
.TP 18
\fBverticalList\fP
Either 'true' or 'false', determines whether the directory listing is 
vertically or horizontally organized.  The default is horizontal (false).
.PP
.br
Here are a few examples of how to string all this information together into
a resource specification that can be used on the command line with the -xrm
flag, or added to your .Xresource or .Xdefaults file.
.TP 35
.B xman*Command.foreground: Blue
All command buttons will be blue.
.TP 35
.B xman*topBox*foreground: Blue
Everything in the top menu has a blue foreground.
.TP 35
.B xman*Text.border: Red
All text widgets have a red border.
.TP 35
.B xman*Label.font: 9x15  
All label buttons have a 9x15 font.
.PP
.SH FILES
/usr/man/* or those specified in the MANPATH.
.br 
mandesc
.PP
.SH "SEE ALSO"
X(1), X(8C), man(1), apropos(1)
.PP
.SH ENVIRONMENT
DISPLAY - the default host and display to use.
.PP
MANPATH - the search path for manual pages.  Directories are separated by
colons (e.g. /usr/man:/mit/kit/man:/foo/bar/man).
.PP
.SH BUGS
The -fn and -font option only specify the fonts for the command button
and not the text of the manpages or directories. 
.br
Protocol error upon selecting "Remove This Manpage".
.br
Specification of the \fImandesc\fP file format is not given in the man page.
.PP
.SH AUTHORS
Copyright 1988 by Massachusetts Institute of Technology.
.br
Chris Peterson, MIT Project Athena from the V10 version written by Barry
Shein of Boston University.
