.\" $XConsortium: xdpyinfo.man,v 1.14 94/04/14 12:09:15 dpw Exp $
.\" Copyright 1988, 1989 Massachusetts Institute of Technology
.\"
.\" Permission to use, copy, modify, distribute, and sell this software and
.\" its documentation for any purpose is hereby granted without fee, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in advertising or
.\" publicity pertaining to distribution of the software without specific,
.\" written prior permission.  M.I.T. makes no representations about the
.\" suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.TH XDPYINFO 1 "Release 6" "X Version 11"
.SH NAME
xdpyinfo \- display information utility for X
.SH SYNOPSIS
.B "xdpyinfo"
[\-display \fIdisplayname\fP]
.SH DESCRIPTION
.PP
.I Xdpyinfo
is a utility for displaying information about an X server.  It is used to 
examine the
capabilities of a server, the predefined values for various parameters used
in communicating between clients and the server, and the different types of
screens and visuals that are available.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
To get the default host, display number, and screen.
.SH "SEE ALSO"
X(1), xwininfo(1), xprop(1), xrdb(1)
.SH AUTHOR
Jim Fulton, MIT X Consortium
