.TH PUZZLE 6 "Jan 22, 1988"
.UC 4
.SH NAME
puzzle \- X-window V11 15-puzzle game
.SH SYNOPSIS
.B puzzle
[
.B geometry
] [
.B display
] [
.B size
] [
.B -s<speed>
] [
.B -p<picture-file>
] [
.B -cm
]
.SH DESCRIPTION
.I Puzzle
with no arguments plays a 4x4 15-puzzle.  The control bar has two boxes in
it.  Clicking in the left box scrambles the puzzle.  Clicking in the right
box solves the puzzle.  Clicking the middle button anywhere else in the 
control bar causes puzzle to exit.
Clicking in the tiled region moves the empty spot to that
location if the region you click in is in the same row or column as the
empty slot. 

.PP
.TP 10
.B geometry
The desired size and location of the puzzle.
.TP 10
.B display
Name of the display you want the puzzle to run on.
.TP 10
.B size
The desired size of the puzzle, specified as <width>x<height>.
The default and minimum size is 4x4.
.TP
.B \-s<speed>
Set the puzzle speed, in units of tiles/sec. Default is 2 tile/sec.
The speed parameter must be an integer.
.TP
.B \-p<picture-file>
Create a pixmap from picture-file and use it as the puzzle. 
The file format is described in picture.c.  To use the mandrill image
provided, run on a pseudo-color display.
.TP
.B \-cm
Directs puzzle to create its own colormap to display the pixmap data.
.PP
.SH AUTHORS
.PD 0
.TP
Don Bennett,   HP Labs
