#undef Boolean
#undef Alignment
#undef Axis
#undef CharCode
#undef Coord
#undef PixelCoord
#undef Tag
#undef Action
#undef ActionImpl
#undef ActionStub
#undef ActionType
#undef Action_tmp
#undef Action_var
#undef ActiveViewer
#undef Adjustment
#undef AdjustmentStub
#undef AdjustmentType
#undef Adjustment_tmp
#undef Adjustment_var
#undef Allocator
#undef ApplicationWindow
#undef BaseThreadsObj
#undef BaseThreadsObjType
#undef BaseThreadsObj_tmp
#undef BaseThreadsObj_var
#undef Beveler
#undef Box
#undef Brush
#undef BrushImpl
#undef BrushStub
#undef BrushType
#undef Brush_tmp
#undef Brush_var
#undef Button
#undef ButtonImpl
#undef ButtonStub
#undef ButtonType
#undef Button_tmp
#undef Button_var
#undef CharString
#undef CharStringBuffer
#undef CharStringImpl
#undef CharStringStub
#undef CharStringType
#undef CharString_tmp
#undef CharString_var
#undef ClippingStack
#undef Color
#undef ColorImpl
#undef ColorStub
#undef ColorType
#undef Color_tmp
#undef Color_var
#undef ConditionImpl
#undef ConditionVariable
#undef ConditionVariableType
#undef ConditionVariable_tmp
#undef ConditionVariable_var
#undef Cursor
#undef CursorImpl
#undef CursorStub
#undef CursorType
#undef Cursor_tmp
#undef Cursor_var
#undef DamageObj
#undef DamageObjStub
#undef DamageObjType
#undef DamageObj_tmp
#undef DamageObj_var
#undef DamageRegion
#undef DebugGlyph
#undef DeckImpl
#undef DeckObj
#undef DeckObjStub
#undef DeckObjType
#undef DeckObj_tmp
#undef DeckObj_var
#undef DefaultPainterImpl
#undef Directory
#undef DirectoryEntry
#undef DirectoryImpl
#undef DisplayImpl
#undef DisplayImplDamage
#undef DisplayImplFilters
#undef DisplayImplRemoveFilter
#undef DisplayImplWindowTable
#undef DisplayObj
#undef DisplayObjStub
#undef DisplayObjType
#undef DisplayObj_tmp
#undef DisplayObj_var
#undef DisplayStyle
#undef DisplayStyleImpl
#undef DisplayStyleStub
#undef DisplayStyleType
#undef DisplayStyle_tmp
#undef DisplayStyle_var
#undef DrawingKit
#undef DrawingKitColorTable
#undef DrawingKitFontTable
#undef DrawingKitImpl
#undef DrawingKitStub
#undef DrawingKitType
#undef DrawingKit_tmp
#undef DrawingKit_var
#undef Event
#undef EventImpl
#undef EventStub
#undef EventType
#undef Event_tmp
#undef Event_var
#undef Figure
#undef FigureKit
#undef FigureKitImpl
#undef FigureKitStub
#undef FigureKitType
#undef FigureKit_tmp
#undef FigureKit_var
#undef FigureLabel
#undef FigureStyle
#undef FigureStyleImpl
#undef FigureStyleStub
#undef FigureStyleType
#undef FigureStyle_tmp
#undef FigureStyle_var
#undef File
#undef FileInfo
#undef Focus
#undef FocusImpl
#undef FocusStub
#undef FocusType
#undef Focus_tmp
#undef Focus_var
#undef Font
#undef FontImpl
#undef FontStub
#undef FontType
#undef Font_tmp
#undef Font_var
#undef Fresco
#undef FrescoImpl
#undef FrescoObject
#undef FrescoObjectStub
#undef FrescoObjectType
#undef FrescoObject_tmp
#undef FrescoObject_var
#undef GTStack
#undef GenericSequence
#undef Glue
#undef Glyph
#undef GlyphImpl
#undef GlyphOffset
#undef GlyphOffsetStub
#undef GlyphOffsetType
#undef GlyphOffset_tmp
#undef GlyphOffset_var
#undef GlyphStub
#undef GlyphTraversal
#undef GlyphTraversalImpl
#undef GlyphTraversalStub
#undef GlyphTraversalType
#undef GlyphTraversal_tmp
#undef GlyphTraversal_var
#undef GlyphType
#undef GlyphVisitor
#undef GlyphVisitorImpl
#undef GlyphVisitorStub
#undef GlyphVisitorType
#undef GlyphVisitor_tmp
#undef GlyphVisitor_var
#undef Glyph_tmp
#undef Glyph_var
#undef HStrut
#undef Host
#undef IconWindow
#undef InputFile
#undef LayoutAlign
#undef LayoutCenter
#undef LayoutFixed
#undef LayoutKit
#undef LayoutKitImpl
#undef LayoutKitStub
#undef LayoutKitType
#undef LayoutKit_tmp
#undef LayoutKit_var
#undef LayoutLayer
#undef LayoutManager
#undef LayoutMargin
#undef LayoutNatural
#undef LayoutSuperpose
#undef LayoutTile
#undef LayoutTileFirstAligned
#undef LayoutTileReversed
#undef LayoutTileReversedFirstAligned
#undef LayoutVariable
#undef List
#undef LockImpl
#undef LockObj
#undef LockObjType
#undef LockObj_tmp
#undef LockObj_var
#undef LockedFrescoObjectImpl
#undef MainViewer
#undef ManagedWindow
#undef Math
#undef MatrixStack
#undef MatrixStackElement
#undef Memory
#undef Menu
#undef MenuItem
#undef MenuItemStub
#undef MenuItemType
#undef MenuItem_tmp
#undef MenuItem_var
#undef MenuStub
#undef MenuType
#undef Menu_tmp
#undef Menu_var
#undef MonoGlyph
#undef MonoGlyphOffset
#undef ObservableInfo
#undef ObserverList
#undef Option
#undef PainterObj
#undef PainterObjStub
#undef PainterObjType
#undef PainterObj_tmp
#undef PainterObj_var
#undef PickTraversal
#undef Placement
#undef PolyFigure
#undef PolyGlyph
#undef PolyGlyphOffset
#undef PopupWindow
#undef PtrList
#undef RGBTable
#undef Raster
#undef RasterBitmap
#undef RasterChannels
#undef RasterImpl
#undef RasterLUT
#undef RasterStub
#undef RasterType
#undef Raster_tmp
#undef Raster_var
#undef Region
#undef RegionImpl
#undef RegionStub
#undef RegionType
#undef Region_tmp
#undef Region_var
#undef ScreenImpl
#undef ScreenObj
#undef ScreenObjStub
#undef ScreenObjType
#undef ScreenObj_tmp
#undef ScreenObj_var
#undef ScreenVisualList
#undef ScrollBox
#undef ScrollBoxStub
#undef ScrollBoxType
#undef ScrollBox_tmp
#undef ScrollBox_var
#undef Semaphore
#undef SemaphoreImpl
#undef SemaphoreType
#undef Semaphore_tmp
#undef Semaphore_var
#undef ShapeOf
#undef SharedFrescoObjectImpl
#undef SharedStyleImpl
#undef Space
#undef StdInput
#undef Strut
#undef StyleCloner
#undef StyleData
#undef StyleImpl
#undef StyleList
#undef StyleMatcher
#undef StyleObj
#undef StyleObjStub
#undef StyleObjType
#undef StyleObj_tmp
#undef StyleObj_var
#undef StyleValue
#undef StyleValueImpl
#undef StyleValueImplList
#undef StyleValueStub
#undef StyleValueTable
#undef StyleValueTableEntry
#undef StyleValueType
#undef StyleValue_tmp
#undef StyleValue_var
#undef StyleVisitor
#undef StyleVisitorImpl
#undef StyleVisitorStub
#undef StyleVisitorType
#undef StyleVisitor_tmp
#undef StyleVisitor_var
#undef Table
#undef Table2
#undef Telltale
#undef TelltaleImpl
#undef TelltaleStub
#undef TelltaleType
#undef Telltale_tmp
#undef Telltale_var
#undef ThreadImpl
#undef ThreadKit
#undef ThreadKitImpl
#undef ThreadKitType
#undef ThreadKit_tmp
#undef ThreadKit_var
#undef ThreadList
#undef ThreadObj
#undef ThreadObjType
#undef ThreadObj_tmp
#undef ThreadObj_var
#undef TopLevelWindow
#undef TransformAllocator
#undef TransformImpl
#undef TransformObj
#undef TransformObjStub
#undef TransformObjType
#undef TransformObj_tmp
#undef TransformObj_var
#undef TransientWindow
#undef VStrut
#undef Vertex
#undef Viewer
#undef ViewerImpl
#undef ViewerOffset
#undef ViewerStub
#undef ViewerType
#undef Viewer_tmp
#undef Viewer_var
#undef VisualTable
#undef WKButtonFrame
#undef WKCheckmark
#undef WKDefaultArrow
#undef WKFrame
#undef WKGlyph
#undef WKIndicator
#undef WKMenuItemFrame
#undef WKPushButtonFrame
#undef WKRadioFlag
#undef WKRadioItem
#undef WKThumb
#undef WidgetKit
#undef WidgetKitImpl
#undef WidgetKitStub
#undef WidgetKitType
#undef WidgetKit_tmp
#undef WidgetKit_var
#undef Window
#undef WindowImpl
#undef WindowStub
#undef WindowStyle
#undef WindowStyleImpl
#undef WindowStyleStub
#undef WindowStyleType
#undef WindowStyle_tmp
#undef WindowStyle_var
#undef WindowType
#undef Window_tmp
#undef Window_var
#undef XPainterImpl
