#undef Boolean
#undef Alignment
#undef Axis
#undef CharCode
#undef Coord
#undef PixelCoord
#undef Tag
#undef Action
#undef ActionImpl
#undef ActionStub
#undef ActionType
#undef ActiveViewer
#undef Adjustment
#undef AdjustmentStub
#undef AdjustmentType
#undef Allocator
#undef ApplicationWindow
#undef BaseThreadsObj
#undef BaseThreadsObjType
#undef Beveler
#undef Box
#undef Brush
#undef BrushImpl
#undef BrushStub
#undef BrushType
#undef Button
#undef ButtonImpl
#undef ButtonStub
#undef ButtonType
#undef CharString
#undef CharStringBuffer
#undef CharStringImpl
#undef CharStringStub
#undef CharStringType
#undef ClippingStack
#undef Color
#undef ColorImpl
#undef ColorStub
#undef ColorType
#undef ConditionImpl
#undef ConditionVariable
#undef ConditionVariableType
#undef Cursor
#undef CursorImpl
#undef CursorStub
#undef CursorType
#undef DamageObj
#undef DamageObjStub
#undef DamageObjType
#undef DamageRegion
#undef DebugGlyph
#undef DeckImpl
#undef DeckObj
#undef DeckObjStub
#undef DeckObjType
#undef Directory
#undef DirectoryEntry
#undef DirectoryImpl
#undef DisplayImpl
#undef DisplayImplDamage
#undef DisplayImplFilters
#undef DisplayImplRemoveFilter
#undef DisplayImplWindowTable
#undef DisplayObj
#undef DisplayObjStub
#undef DisplayObjType
#undef DisplayStyle
#undef DisplayStyleImpl
#undef DisplayStyleStub
#undef DisplayStyleType
#undef DrawingKit
#undef DrawingKitColorTable
#undef DrawingKitFontTable
#undef DrawingKitImpl
#undef DrawingKitStub
#undef DrawingKitType
#undef Event
#undef EventImpl
#undef EventStub
#undef EventType
#undef Figure
#undef FigureKit
#undef FigureKitImpl
#undef FigureKitStub
#undef FigureKitType
#undef FigureLabel
#undef FigureStyle
#undef FigureStyleImpl
#undef FigureStyleStub
#undef FigureStyleType
#undef File
#undef FileInfo
#undef Focus
#undef FocusImpl
#undef FocusStub
#undef FocusType
#undef Font
#undef FontImpl
#undef FontStub
#undef FontType
#undef Fresco
#undef FrescoImpl
#undef FrescoObject
#undef FrescoObjectStub
#undef FrescoObjectType
#undef GTStack
#undef GenericSequence
#undef Glue
#undef Glyph
#undef GlyphImpl
#undef GlyphOffset
#undef GlyphOffsetStub
#undef GlyphOffsetType
#undef GlyphStub
#undef GlyphTraversal
#undef GlyphTraversalImpl
#undef GlyphTraversalStub
#undef GlyphTraversalType
#undef GlyphType
#undef GlyphVisitor
#undef GlyphVisitorImpl
#undef GlyphVisitorStub
#undef GlyphVisitorType
#undef HStrut
#undef Host
#undef IconWindow
#undef InputFile
#undef LayoutAlign
#undef LayoutCenter
#undef LayoutFixed
#undef LayoutKit
#undef LayoutKitImpl
#undef LayoutKitStub
#undef LayoutKitType
#undef LayoutLayer
#undef LayoutManager
#undef LayoutMargin
#undef LayoutNatural
#undef LayoutSuperpose
#undef LayoutTile
#undef LayoutTileFirstAligned
#undef LayoutTileReversed
#undef LayoutTileReversedFirstAligned
#undef LayoutVariable
#undef List
#undef LockImpl
#undef LockObj
#undef LockObjType
#undef LockedFrescoObjectImpl
#undef MainViewer
#undef ManagedWindow
#undef Math
#undef MatrixStack
#undef MatrixStackElement
#undef Memory
#undef Menu
#undef MenuItem
#undef MenuItemStub
#undef MenuItemType
#undef MenuStub
#undef MenuType
#undef MonoGlyph
#undef MonoGlyphOffset
#undef ObservableInfo
#undef ObserverList
#undef Option
#undef PainterObj
#undef PainterObjStub
#undef PainterObjType
#undef Placement
#undef PolyFigure
#undef PolyGlyph
#undef PolyGlyphOffset
#undef PopupWindow
#undef PtrList
#undef RGBTable
#undef Raster
#undef RasterBitmap
#undef RasterChannels
#undef RasterImpl
#undef RasterLUT
#undef RasterStub
#undef RasterType
#undef Region
#undef RegionImpl
#undef RegionStub
#undef RegionType
#undef ScreenImpl
#undef ScreenObj
#undef ScreenObjStub
#undef ScreenObjType
#undef ScreenVisualList
#undef ScrollBox
#undef ScrollBoxStub
#undef ScrollBoxType
#undef Semaphore
#undef SemaphoreImpl
#undef SemaphoreType
#undef ShapeOf
#undef SharedFrescoObjectImpl
#undef SharedStyleImpl
#undef Space
#undef StdInput
#undef Strut
#undef StyleCloner
#undef StyleData
#undef StyleImpl
#undef StyleList
#undef StyleMatcher
#undef StyleObj
#undef StyleObjStub
#undef StyleObjType
#undef StyleValue
#undef StyleValueImpl
#undef StyleValueImplList
#undef StyleValueStub
#undef StyleValueTable
#undef StyleValueTableEntry
#undef StyleValueType
#undef StyleVisitor
#undef StyleVisitorImpl
#undef StyleVisitorStub
#undef StyleVisitorType
#undef Table
#undef Table2
#undef Telltale
#undef TelltaleImpl
#undef TelltaleStub
#undef TelltaleType
#undef ThreadImpl
#undef ThreadKit
#undef ThreadKitImpl
#undef ThreadKitType
#undef ThreadList
#undef ThreadObj
#undef ThreadObjType
#undef TopLevelWindow
#undef TransformAllocator
#undef TransformImpl
#undef TransformObj
#undef TransformObjStub
#undef TransformObjType
#undef TransientWindow
#undef UniqueString
#undef UniqueStringPool
#undef UniqueStringTable
#undef VStrut
#undef Vertex
#undef Viewer
#undef ViewerImpl
#undef ViewerStub
#undef ViewerType
#undef VisualTable
#undef WKButtonFrame
#undef WKCheckmark
#undef WKDefaultArrow
#undef WKFrame
#undef WKGlyph
#undef WKIndicator
#undef WKMenuItemFrame
#undef WKPushButtonFrame
#undef WKRadioFlag
#undef WKRadioItem
#undef WKThumb
#undef WidgetKit
#undef WidgetKitImpl
#undef WidgetKitStub
#undef WidgetKitType
#undef Window
#undef WindowImpl
#undef WindowStub
#undef WindowStyle
#undef WindowStyleImpl
#undef WindowStyleStub
#undef WindowStyleType
#undef WindowType
#undef XPainterImpl
#undef _ActionElem
#undef _ActionExpr
#undef _AdjustmentElem
#undef _AdjustmentExpr
#undef _BaseThreadsObjElem
#undef _BaseThreadsObjExpr
#undef _BrushElem
#undef _BrushExpr
#undef _ButtonElem
#undef _ButtonExpr
#undef _CharStringElem
#undef _CharStringExpr
#undef _ColorElem
#undef _ColorExpr
#undef _ConditionVariableElem
#undef _ConditionVariableExpr
#undef _CursorElem
#undef _CursorExpr
#undef _DamageObjElem
#undef _DamageObjExpr
#undef _DeckObjElem
#undef _DeckObjExpr
#undef _DisplayObjElem
#undef _DisplayObjExpr
#undef _DisplayStyleElem
#undef _DisplayStyleExpr
#undef _DrawingKitElem
#undef _DrawingKitExpr
#undef _EventElem
#undef _EventExpr
#undef _FigureKitElem
#undef _FigureKitExpr
#undef _FigureStyleElem
#undef _FigureStyleExpr
#undef _FocusElem
#undef _FocusExpr
#undef _FontElem
#undef _FontExpr
#undef _FrescoObjectElem
#undef _FrescoObjectExpr
#undef _GlyphElem
#undef _GlyphExpr
#undef _GlyphOffsetElem
#undef _GlyphOffsetExpr
#undef _GlyphTraversalElem
#undef _GlyphTraversalExpr
#undef _GlyphVisitorElem
#undef _GlyphVisitorExpr
#undef _LayoutKitElem
#undef _LayoutKitExpr
#undef _LockObjElem
#undef _LockObjExpr
#undef _MenuElem
#undef _MenuExpr
#undef _MenuItemElem
#undef _MenuItemExpr
#undef _PainterObjElem
#undef _PainterObjExpr
#undef _RasterElem
#undef _RasterExpr
#undef _RegionElem
#undef _RegionExpr
#undef _ScreenObjElem
#undef _ScreenObjExpr
#undef _ScrollBoxElem
#undef _ScrollBoxExpr
#undef _SemaphoreElem
#undef _SemaphoreExpr
#undef _StyleObjElem
#undef _StyleObjExpr
#undef _StyleValueElem
#undef _StyleValueExpr
#undef _StyleVisitorElem
#undef _StyleVisitorExpr
#undef _TelltaleElem
#undef _TelltaleExpr
#undef _ThreadKitElem
#undef _ThreadKitExpr
#undef _ThreadObjElem
#undef _ThreadObjExpr
#undef _TransformObjElem
#undef _TransformObjExpr
#undef _ViewerElem
#undef _ViewerExpr
#undef _WidgetKitElem
#undef _WidgetKitExpr
#undef _WindowElem
#undef _WindowExpr
#undef _WindowStyleElem
#undef _WindowStyleExpr
